Improved E2 rcS spark7162

diff --git a/root/release/rcS_enigma2_spark7162 b/root/release/rcS_enigma2_spark7162
--- a/root/release/rcS_enigma2_spark7162
+++ b/root/release/rcS_enigma2_spark7162
@@ -1,5 +1,5 @@
 #!/bin/sh
-#Version 160420.1
+#Version 180908.1
 
 echo "Spark 7162 Enigma2"
 
@@ -16,13 +16,13 @@ fi
 
 if [ -e /var/etc/.firstboot ]; then
    echo "Wait 1 min." > /dev/vfd
-   echo "WAIT 1 min"
+   echo "[rcS] WAIT 1 min"
    rm /var/etc/.firstboot
    sleep 1
    touch /dev/.devfsd
 else
    echo "Load 10" > /dev/vfd
-   echo "LOAD 10"
+   echo "[rcS] LOAD 10"
 fi
 
 /etc/init.d/mountvirtfs start
@@ -50,14 +50,14 @@ if [ -e "$MODDIR/cpu_frequ.ko" ]; then
            overclk=4609;;
    esac
    echo $overclk > /proc/cpu_frequ/pll0_ndiv_mdiv
-   echo "Setting CPU clock speed to $cpufreq MHz (overclk=$overclk)"
+   echo "[rcS] Setting CPU clock speed to $cpufreq MHz (overclk=$overclk)"
 fi
 
-echo "Starting DEBUG Interface"
+echo "[rcS] Starting DEBUG Interface"
 /etc/init.d/mountall start
 /etc/init.d/hostname start
 
-echo -n "Starting telnetd "
+echo -n "[rcS] Starting telnetd "
 autologin=`cat /etc/enigma2/settings | grep systemoptions.autologin | cut -d "=" -f2`
 if [ ! $autologin ]; then
    /usr/sbin/telnetd -l /bin/autologin
@@ -67,7 +67,7 @@ else
    echo "with normal login"
 fi
 
-echo "Init stmfb (LOAD 9)"
+echo "[rcS] Init stmfb (LOAD 9)"
 echo "Load 9" > /dev/vfd
 insmod $MODDIR/stmcore-display-sti7105.ko
 if grep -q "config.av.videoport=Scart" /etc/enigma2/settings; then
@@ -76,14 +76,14 @@ else
   insmod $MODDIR/stmfb.ko display0=1280x720-32@50:16m:pal:rgb:rgb; #HDMI
 fi
 
-echo "Loading modules"
+echo "[rcS] Loading modules"
 
 if [ ! -e /boot/audio.elf ] || [ ! -e /boot/video.elf ]; then
-   echo "FIRMWARE MISSING!"
+   echo "[rcS] FIRMWARE MISSING!"
    echo "FW MISSING!" > /dev/vfd
 fi
 
-echo "Load audio firmware (LOAD 8)"
+echo "[rcS] Load audio firmware (LOAD 8)"
 echo "Load 8" > /dev/vfd
 dtsdown=`cat /etc/enigma2/settings | grep systemoptions.dtsdownmix | cut -d "=" -f2`
 if [ ! $dtsdown ] && [ -e /boot/audio_dts.elf ]; then
@@ -92,23 +92,23 @@ else
    /bin/ustslave /dev/st231-1 /boot/audio.elf > /dev/null
 fi
 
-echo "Load video firmware (LOAD 7)"
+echo "[rcS] Load video firmware (LOAD 7)"
 echo "Load 7" > /dev/vfd
 /bin/ustslave /dev/st231-0 /boot/video.elf > /dev/null
 
-echo "Init embx (LOAD 6)"
+echo "[rcS] Init embx (LOAD 6)"
 echo "Load 6" > /dev/vfd
 insmod $MODDIR/embxshell.ko
 insmod $MODDIR/embxmailbox.ko mailbox0=0xfe211000:136:set2 mailbox1=0xfe212000:0
 insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0x40000000:0x10000000
 insmod $MODDIR/mme_host.ko transport0=shm
 
-echo "Init AVS (LOAD 5)"
+echo "[rcS] Init AVS (LOAD 5)"
 echo "Load 5" > /dev/vfd
 insmod $MODDIR/avs.ko type=avs_pio
 
 player=`cat /proc/stb/player/version | awk '{ print substr( $0, length($0) - 2, length($0) ) }'`
-echo "Init player $player (LOAD 4)"
+echo "[rcS] Init player $player (LOAD 4)"
 echo "Load 4" > /dev/vfd
 
 insmod $MODDIR/mmelog.ko
@@ -126,20 +126,20 @@ fi
 insmod $MODDIR/spark7162.ko UnionTunerType=$tunertype
 
 if [ -e $MODDIR/pti.ko ]; then
-#   if [ ! $?=='2' ]; then
-      pti_arg="waitMS=20 videoMem=4096"
-      echo "Full feature pti"
-#   else
-#      pti_arg=""
-#      echo "Simple pti"
-#   fi
-   insmod $MODDIR/pti.ko $pti_arg
+   insmod $MODDIR/pti.ko waitMS=20 videoMem=4096
+   if [ ! $?=='2' ]; then
+      rmmod pti.ko
+      insmod $MODDIR/pti.ko
+      echo "[rcS] Simple pti"
+   else
+      echo "[rcS] Full feature pti"
+   fi
 fi
 insmod $MODDIR/stm_monitor.ko
 insmod $MODDIR/stmsysfs.ko
 insmod $MODDIR/stmdvb.ko
 
-echo "LOAD 3"
+echo "[rcS] LOAD 3"
 echo "Load 3" > /dev/vfd
 #insmod $MODDIR/player2.ko discardlateframe=0
 insmod $MODDIR/player2.ko
@@ -152,23 +152,23 @@ insmod $MODDIR/smartcard.ko
 
 if [ -e $MODDIR/dvb-it913x.ko ]; then
   echo
-  echo "IT913X driver loading"
-  echo "---------------------"
+  echo "[rcS] IT913X driver loading"
+  echo "[rcS] ---------------------"
   insmod $MODDIR/dvb-pll.ko
   insmod $MODDIR/dvb-it913x.ko
   echo
-  echo "End of IT913X driver loading"
-  echo "----------------------------"
+  echo "[rcS] End of IT913X driver loading"
+  echo "[rcS] ----------------------------"
 fi
 
 if [ -e $MODDIR/dvb-usb-rtl2832u.ko ]; then
   echo
-  echo "RTL2832U driver loading"
-  echo "-----------------------"
+  echo "[rcS] RTL2832U driver loading"
+  echo "[rcS] -----------------------"
   insmod $MODDIR/dvb-usb-rtl2832u.ko
   echo
-  echo "End of RTL2832U driver loading"
-  echo "------------------------------"
+  echo "[rcS] End of RTL2832U driver loading"
+  echo "[rcS] ------------------------------"
 fi
 
 if [ -e $MODDIR/usb_serial.ko ]; then
@@ -182,7 +182,7 @@ if [ -e $MODDIR/usb_serial.ko ]; then
   insmod $MODDIR/option.ko
 fi
 
-echo "Init HDMI-CEC"
+echo "[rcS] Init HDMI-CEC"
 insmod $MODDIR/cec.ko activemode=1
 
 insmod $MODDIR/bpamem.ko
@@ -193,14 +193,14 @@ if [ -e /boot/bootlogo.mvi ]; then
 fi
 stfbcontrol a 0
 
-echo "Init lircd (LOAD 2)"
+echo "[rcS] Init lircd (LOAD 2)"
 echo "Load 2" > /dev/vfd
 /usr/bin/lircd
 rm -rf /dev/rc
 mknod /dev/rc c 147 1 #VFD
 /bin/evremote2 10 120 &
 
-echo "Init smartcard cardreader"
+echo "[rcS] Init smartcard cardreader"
 mknod /dev/sci0 c 169 0
 mknod /dev/sci1 c 169 1
 
@@ -210,12 +210,13 @@ mknod /dev/sci1 c 169 1
 
 stfbcontrol a 255
 
-wlan=`cat /etc/enigma2/settings | grep systemoptions.wlan | cut -d "=" -f2`
+#wlan=`cat /etc/enigma2/settings | grep systemoptions.wlan | cut -d "=" -f2`
+wlan=8192eu
 if [ ! $wlan ] || [ ! -e $MODDIR/$wlan.ko ]; then
-   echo "No WLAN"
+   echo "[rcS] No WLAN"
 else
    insmod $MODDIR/$wlan.ko
-   echo "$wlan WLAN"
+   echo "[rcS] $wlan WLAN"
 #   echo "$wlan WLAN" > /dev/vfd
 #   sleep 3
 fi
@@ -228,7 +229,7 @@ if [ -e $MODDIR/cifs.ko ]; then
    insmod $MODDIR/cifs.ko
 fi
 
-echo "Init FTP (LOAD 1)"
+echo "[rcS] Init FTP (LOAD 1)"
 echo "Load 1" > /dev/vfd
 /etc/init.d/vsftpd start
 /usr/sbin/inetd
@@ -242,7 +243,7 @@ else
       /etc/init.d/networking stop
       DHCP=`grep -c 'iface eth0 inet dhcp' /etc/network/interfaces`
       if [ "$DHCP" -eq "1" ]; then
-         echo "Starting DHCP on eth0"
+         echo "[rcS] Starting DHCP on eth0"
          /etc/init.d/udhcpc start
       fi
       /etc/init.d/networking start &
@@ -269,47 +270,43 @@ fi
 #inettime=`cat /etc/enigma2/settings | grep systemoptions.inettime | cut -d "=" -f2`
 # if [ ! $inettime ] && [ -e /sbin/ntpdate ]; then
 if [ -e /sbin/ntpdate ]; then
-   echo "Set internet time"
+   echo "[rcS] Set internet time"
    /sbin/ntpdate de.pool.ntp.org
    /bin/fp_control -sst &
 else
    if [ -e /usr/sbin/time.sh ]; then
-      echo "Use transponder time"
+      echo "[rcS] Use transponder time"
       /usr/sbin/time.sh &
    fi
 fi
 
-echo "Start Enigma2"
+echo "[rcS] Start Enigma2"
 echo "Start SH4 Enigma2" > /dev/vfd
 
 until false
 do
-   echo "Entering e2 main loop"
+   echo "[rcS] Entering e2 main loop"
    if [ -e /usr/local/share/enigma2/backdrop.mvi ]; then
       showiframe -p /usr/local/share/enigma2/backdrop.mvi &
    fi
    /usr/local/bin/enigma2
    rtv=$?
-   echo "e2 ended <- RTV: " $rtv
+   echo "[rcS] e2 ended <- RTV: " $rtv
    /bin/fp_control -i 46 0
    case "$rtv" in
-      0)  echo "0"
-          echo "E2 ERROR"
+      0)  echo "[rcS] E2 ERROR"
           echo "E2 Error" > /dev/vfd
           init 6;;
-      1)  echo "1"
-          echo "SHUTDOWN"
+      1)  echo "[rcS] SHUTDOWN"
           echo "Shutdown" > /dev/vfd
           if [ -e /usr/local/share/enigma2/shutdown.mvi ]; then
              showiframe -p /usr/local/share/enigma2/shutdown.mvi &
           fi
           init 0;;
-      2)  echo "2"
-          echo "REBOOT"
+      2)  echo "[rcS] REBOOT"
           echo "Reboot" > /dev/vfd
           init 6;;
-      3)  echo "3"
-          echo "E2 RESTART"
+      3)  echo "[rcS] E2 RESTART"
           echo "Restart GUI" > /dev/vfd
           echo "0" > /proc/progress
           if [ -e /usr/local/share/enigma2/backdrop.mvi ]; then
@@ -317,8 +314,7 @@ do
           else
              showiframe -p /boot/bootlogo.mvi &
           fi;;
-      10) echo "10"
-          echo "SPARK RESTART"
+      10) echo "[rcS] SPARK RESTART"
           echo "SPARK Restart" > /dev/vfd
           insmod $MODDIR/i2s.ko
           if [ ! -f /etc/fw_env.config ]; then
@@ -338,15 +334,14 @@ do
           var=`fw_printenv | grep 'kernel_len_spark='` ; fw_setenv kernel_len ${var#*=}
           sync
           init 6;;
-      *)  echo "*"
-          echo "ERROR"
+      *)  echo "[rcS] ERROR"
           echo "Error" > /dev/vfd
           init 6;;
    esac
 done
 
 #never reached
-echo "REBOOT SPARK7162"
+echo "[rcS] REBOOT SPARK7162"
 echo "Reboot SPARK7162" > /dev/vfd
 reboot -f
 
