Synchronize with buildsystem:master

diff --git a/root/release/rcS_neutrino_spark7162 b/root/release/rcS_neutrino_spark7162
--- a/root/release/rcS_neutrino_spark7162
+++ b/root/release/rcS_neutrino_spark7162
@@ -1,28 +1,28 @@
 #!/bin/sh
-#Version 220711.1
+#Version 230309.1
 
+echo "[rcS] Start"
 echo "Spark 7162 Neutrino"
 
 MODDIR=/lib/modules
 
 insmod $MODDIR/e2_proc.ko
 
-echo "Init frontpanel"
+echo "[rcS] Init frontpanel"
 insmod $MODDIR/aotom.ko paramDebug=0
 
 if [ -e /var/etc/.firstboot ]; then
    echo "Wait 1 min." > /dev/vfd
-   echo "WAIT 1 min"
+   echo "[rcS] WAIT 1 minute"
    rm /var/etc/.firstboot
    sleep 1
    touch /dev/.devfsd
 else
    echo "Load 10" > /dev/vfd
-   echo "LOAD 10"
+   echo "[rcS] LOAD 10"
 fi
 
 /etc/init.d/mountvirtfs start
-/etc/init.d/portmap start
 
 #if [ -e "$MODDIR/cpu_frequ.ko" ]; then
 #   insmod $MODDIR/cpu_frequ.ko
@@ -48,49 +48,63 @@ fi
 #   echo "Setting CPU clock speed to $cpufreq MHz (overclk=$overclk)"
 #fi
 
-echo "Starting DEBUG Interface"
+# Start automounter with umount timeout of 5 seconds
+if [ -e $MODDIR/autofs4.ko ]; then
+   insmod $MODDIR/autofs4.ko
+fi
+if [ -e /etc/init.d/automount ]; then
+   /usr/sbin/automount --ghost --timeout=5 /autofs file /etc/auto.usb
+fi
+
+echo "[rcS] Starting DEBUG Interface"
 /etc/init.d/mountall start
 /etc/init.d/hostname start
 
-echo "Init stmfb (LOAD 9)"
+echo -n "[rcS] Starting telnetd "
+/usr/sbin/telnetd -l /bin/autologin
+echo "with autologin"
+
+echo "[rcS] Init stmfb (LOAD 9)"
 echo "Load 9" > /dev/vfd
 insmod $MODDIR/stmcore-display-sti7105.ko
-insmod $MODDIR/stmfb.ko display0=1280x720-32@50:12m:pal:rgb:rgb; #HDMI
+insmod $MODDIR/stmfb.ko display0=1280x720-32@50:12m:pal:rgb:rgb #HDMI
 
-echo "Loading modules"
+echo "[rcS] Loading modules"
 
 if [ ! -e /lib/firmware/audio.elf ] || [ ! -e /lib/firmware/video.elf ]; then
-   echo "FIRMWARE MISSING!"
+   echo "[rcS] Firmware(s) missing!"
    echo "FW MISSING!" > /dev/vfd
+   sleep 5
 fi
 
-echo "Load audio firmware (LOAD 8)"
+echo "[rcS] Load video firmware (LOAD 8)"
 echo "Load 8" > /dev/vfd
+/bin/dd if=/dev/zero of=/dev/st231-0 bs=1024 count=4096 2> /dev/null
+/bin/ustslave /dev/st231-0 /lib/firmware/video.elf > /dev/null
+
+echo "[rcS] Load audio firmware (LOAD 7)"
+echo "Load 7" > /dev/vfd
+/bin/dd if=/dev/zero of=/dev/st231-1 bs=1024 count=4096 2> /dev/null
 if [ -e /lib/firmware/audio_dts.elf ]; then
    /bin/ustslave /dev/st231-1 /lib/firmware/audio_dts.elf > /dev/null
 else
    /bin/ustslave /dev/st231-1 /lib/firmware/audio.elf > /dev/null
 fi
 
-echo "Load video firmware (LOAD 7)"
-echo "Load 7" > /dev/vfd
-/bin/ustslave /dev/st231-0 /lib/firmware/video.elf > /dev/null
-
-echo "Init embx (LOAD 6)"
+echo "[rcS] Init embx (LOAD 6)"
 echo "Load 6" > /dev/vfd
 insmod $MODDIR/embxshell.ko
 insmod $MODDIR/embxmailbox.ko mailbox0=0xfe211000:136:set2 mailbox1=0xfe212000:0
 insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0x40000000:0x10000000
 insmod $MODDIR/mme_host.ko transport0=shm
 
-echo "Init AVS (LOAD 5)"
+echo "[rcS] Init AVS (LOAD 5)"
 echo "Load 5" > /dev/vfd
 insmod $MODDIR/avs.ko type=avs_pio
 
 player=`cat /proc/stb/player/version | awk '{ print substr( $0, length($0) - 2, length($0) ) }'`
-echo "Init player $player (LOAD 4)"
+echo "[rcS] Init player $player (LOAD 4)"
 echo "Load 4" > /dev/vfd
-
 insmod $MODDIR/mmelog.ko
 insmod $MODDIR/ksound.ko
 insmod $MODDIR/p2div64.ko
@@ -101,26 +115,33 @@ insmod $MODDIR/pseudocard.ko
 
 #Set desired mode for tuner 3 here: t=DVB-T, c=DVB-C
 tunertype='t'
+echo "[rcS] Init frontend(s)"
 insmod $MODDIR/spark7162.ko UnionTunerType=$tunertype
 
-#pti_arg="waitMS=20 videoMem=4096"
-#echo "Full feature pti"
-pti_arg=""
-echo "Simple pti"
-insmod $MODDIR/pti.ko $pti_arg
+echo "[rcS] Initialize PTI"
+insmod $MODDIR/pti.ko waitMS=20 videoMem=4096
+if [ $? -ne 0 ]; then
+   insmod $MODDIR/pti.ko
+   echo "[rcS] Simple pti"
+else
+   echo "[rcS] Full feature pti"
+fi
 insmod $MODDIR/stm_monitor.ko
 insmod $MODDIR/stmsysfs.ko
 insmod $MODDIR/stmdvb.ko
 
+echo "[rcS] Init player2 (LOAD 3)"
 echo "Load 3" > /dev/vfd
-echo "LOAD 3"
 insmod $MODDIR/player2.ko
 insmod $MODDIR/sth264pp.ko
 insmod $MODDIR/stmalloc.ko
 insmod $MODDIR/platform.ko
 insmod $MODDIR/silencegen.ko
-insmod $MODDIR/smartcard.ko
+
 insmod $MODDIR/bpamem.ko
+
+echo "[rcS] Init cardreader"
+insmod $MODDIR/smartcard.ko
 
 if [ -e /boot/neutrinologo_720.mvi ]; then
    showiframe -p /boot/neutrinologo_720.mvi &
@@ -133,69 +154,81 @@ if [ -e $MODDIR/cec.ko ]; then
    insmod $MODDIR/cec.ko activemode=1
 fi
 
-echo "Init lircd (LOAD 2)"
+if [ -e $MODDIR/exportfs.ko ]; then
+   echo "[rcS] Init exportfs"
+   insmod $MODDIR/exportfs.ko
+fi
+if [ -e $MODDIR/cifs.ko ]; then
+   echo "[rcS] Init CIFS support"
+   insmod $MODDIR/cifs.ko
+fi
+if [ -e $MODDIR/ntfs.ko ]; then
+   echo "[rcS] Init NTFS support"
+   insmod $MODDIR/ntfs.ko
+fi
+if [ -e $MODDIR/tun.ko ]; then
+   echo "[rcS] Init tun support"
+   insmod $MODDIR/tun.ko
+fi
+if [ -e $MODDIR/usbserial.ko ]; then
+   insmod $MODDIR/usbserial.ko
+   if [ -e $MODDIR/ch341.ko ]; then
+      insmod $MODDIR/ch341.ko
+   fi
+   if [ -e $MODDIR/ftdi.ko ]; then
+      echo "[rcS] Init FTDI USB serial support"
+      insmod $MODDIR/ftdi.ko
+   fi
+   if [ -e $MODDIR/pl2303.ko ]; then
+   echo "[rcS] Init PL2303 USB serial support"
+      insmod $MODDIR/pl2303.ko
+   fi
+   if [ -e $MODDIR/option.ko ]; then
+      insmod $MODDIR/option.ko
+   fi
+   if [ -e $MODDIR/usb_wwan.ko ]; then # 3G modem
+      insmod $MODDIR/usb_wwan.ko
+   fi
+fi
+
+echo "[rcS] Initialize remote control (LOAD 2)"
 echo "Load 2" > /dev/vfd
 mkdir -p /var/run/lirc
 /usr/bin/lircd -u
-
-#major=$(awk "\$2==\"sparkid\" {print \$1}" /proc/devices)
-#rm -f /dev/sparkid
-#mknod /dev/sparkid c $major 0
-#   rm /f /dev/dvb/adapter0/ca1
-#   mknod /dev/dvb/adapter0/ca1 c 212 22
-
-#echo "Init smartcard cardreader"
-#mknod /dev/sci0 c 169 0
-#mknod /dev/sci1 c 169 1
+/bin/evremote2 10 150 &
 
 stfbcontrol a 255
 
-#wlan=`cat /etc/enigma2/settings | grep systemoptions.wlan | cut -d "=" -f2`
-#if [ ! $wlan ] || [ ! -e $MODDIR/$wlan.ko ]; then
-#   echo "No WLAN"
-#else
-#   insmod $MODDIR/$wlan.ko
-#   echo "$wlan WLAN"
-##   echo "$wlan WLAN" > /dev/vfd
-##   sleep 3
-#fi
-
-# Start automounter with umount timeout of 5 seconds
-mkdir -p /tmp/autofs
-insmod $MODDIR/autofs4.ko
-if [ -e /etc/init.d/automount ]; then
-   /usr/sbin/automount --ghost --timeout=5 /tmp/autofs file /etc/auto.usb
-fi
-
-if [ -e $MODDIR/ntfs.ko ]; then
-   insmod $MODDIR/ntfs.ko
-fi
-
-if [ -e $MODDIR/cifs.ko ]; then
-   insmod $MODDIR/cifs.ko
-fi
-
-echo "Init FTP (LOAD 1)"
-echo "Load 1" > /dev/vfd
-/etc/init.d/vsftpd start
-/usr/sbin/inetd
+echo "[rcS] Load extra modules"
+# Load modules from /var/etc/modules.extra
+[ -f /var/etc/modules.extra ] && eval `sed -e 's/#.*//' -e '/^\s*$/d' -e 's/^\(.*\)/insmod \0;/' < /var/etc/modules.extra`
 
 NFS=`grep -c nfs /proc/cmdline`
 if [ "$NFS" -eq "1" ]; then
-   echo "Booting from nfs, don't set network"
+   echo "[rcS] Booting from NFS, do not set network"
 else
    if [ -e /etc/network/interfaces ]; then
       ip addr flush eth0
       /etc/init.d/networking stop
       DHCP=`grep -c 'iface eth0 inet dhcp' /etc/network/interfaces`
       if [ "$DHCP" -eq "1" ]; then
-         echo "Starting DHCP on eth0"
+         echo "[rcS] Starting DHCP on eth0"
          /etc/init.d/udhcpc start
       fi
       /etc/init.d/networking start
    fi
 fi
 sleep 2
+
+#wlan=rtl8188cu
+if [ ! $wlan ] || [ ! -e $MODDIR/$wlan.ko ]; then
+   echo "No WLAN"
+else
+   insmod $MODDIR/$wlan.ko
+   echo "$wlan WLAN"
+#   echo "$wlan WLAN" > /dev/vfd
+#   sleep 3
+fi
 
 # Do own extras
 if [ -e /etc/ownscript.sh ]; then
@@ -213,38 +246,42 @@ else
    fi
 fi
 
+echo "[rcS] Init portmap & FTP (LOAD 1)"
+echo "Load 1" > /dev/vfd
+/etc/init.d/portmap start
+/etc/init.d/vsftpd start
+/usr/sbin/inetd
+
 #tuner workaround
 export FE_OFFSET=1
 
-echo "Start Neutrino" > /dev/vfd
+echo "[rcS] Loading Neutrino"
+echo "Ld Neutr" > /dev/vfd
 
 until false
 do
-   echo "Starting neutrino ->"
+#   killall -9 showiframe
+   echo "[rcS] Starting Neutrino ->"
    /usr/bin/neutrino
    rtv=$?
-   echo "neutrino ended <- RTV: " $rtv
+   echo "[rcS] Neutrino ended <- return value: " $rtv
    case "$rtv" in
-      0) echo "0"
-         echo "SHUTDOWN"
+      0) echo "[rcS] SHUTDOWN"
          echo "Shutdown" > /dev/vfd
          init 0;;
-      1) echo "1"
-         echo "REBOOT"
+      1) echo "[rcS] REBOOT"
          echo "Reboot" > /dev/vfd
          init 6;;
-      3) echo "3"
-         echo "RESTART"
+      3) echo "[rcS] RESTART"
          echo "Restart" > /dev/vfd
          ;;
-      *) echo "*"
-         echo "ERROR"
+      *) echo "[rcS] ERROR"
          echo "Error" > /dev/vfd
          init 6;;
    esac
 done
 
 #never reached
-echo "Reboot SPARK7162" > /dev/vfd
+echo "[rcS] Reboot SPARK7162" > /dev/vfd
 echo "REBOOT SPARK7162"
 init 6
