Initial commit for OpenPLi release-8.3 builds

diff --git a/root/release/rcS_neutrino_adb_box b/root/release/rcS_neutrino_adb_box
--- a/root/release/rcS_neutrino_adb_box
+++ b/root/release/rcS_neutrino_adb_box
@@ -1,149 +1,335 @@
 #!/bin/sh
+#Version 1901027.1
+
+echo "ADB ITI-5800S(X) Neutrino"
 
 MODDIR=/lib/modules
-boxtype=`cat /etc/boxtype`
+insmod $MODDIR/e2_proc.ko
 
-if [ $boxtype == 'bska' ]; then
-  echo "Init VFD bialy"
-  insmod $MODDIR/vfd.ko rec=0
-else
-  echo "Init VFD czarny"
-  insmod $MODDIR/vfd.ko rec=1
-fi
+#if [ -e $MODDIR/cpu_frequ.ko ]; then
+#  insmod $MODDIR/cpu_frequ.ko
+#  sleep 2
+#  echo 22802 > /proc/cpu_frequ/pll0_ndiv_mdiv  # 267 MHz = 22802
+#  echo 22793 > /proc/cpu_frequ/pll1_ndiv_mdiv  # 267 MHz = 22793
+#fi
+
+echo "[rcS] Init frontpanel"
+insmod $MODDIR/adb_5800_fp.ko #paramDebug=10
+insmod $MODDIR/simu_button.ko
+
+#boxtype=`cat /proc/stb/info/adb_variant` # TODO: fix, does not work
+boxtype=bsla
+echo "[rcS] boxtype: $boxtype"
+echo "$boxtype" > /etc/boxtype
 
 if [ -e /var/etc/.firstboot ]; then
-   echo "WAIT 3 min" > /dev/vfd
-   echo "WAIT 3 min"
+   echo "WAIT 1st start" >/dev/vfd
+   echo "[rcS] WAIT 1st start"
    rm /var/etc/.firstboot
+   sleep 1
    touch /dev/.devfsd
+else
+   if [ $boxtype == 'bska' ] || [ $boxtype == 'bxzb' ]; then
+      echo "Ld10" > /dev/vfd
+   else
+      echo "LOAD 10" > /dev/vfd
+   fi
+   echo "[rcS] Start (LOAD 10)"
 fi
 
 /etc/init.d/mountvirtfs start
-/etc/init.d/portmap start
 
-if [ ! -e /var/etc/.firstboot ]; then
+# Start automounter with umount timeout of 5 seconds
+echo "[rcS] Starting automounter"
+/etc/init.d/autofs start
 
-   insmod $MODDIR/e2_proc.ko
+echo "[rcS] Starting DEBUG Interface"
+/etc/init.d/mountall start
+/etc/init.d/hostname start
 
-   echo "load video firmware"
-   /bin/dd if=/dev/zero of=/dev/st231-0 bs=1024 count=4096
-   /bin/ustslave /dev/st231-0 /lib/firmware/video.elf
+echo -n "[rcS] Starting telnetd"
+/usr/sbin/telnetd -l /bin/autologin
+echo "with autologin"
 
-   echo "load audio firmware"
-   /bin/dd if=/dev/zero of=/dev/st231-1 bs=1024 count=4096
-   /bin/ustslave /dev/st231-1 /lib/firmware/audio.elf
+echo "[rcS] Init stmfb (LOAD 9)"
+if [ $boxtype == 'bska' ] || [ $boxtype == 'bxzb' ]; then
+   echo "Ld 9" > /dev/vfd
+else
+   echo "LOAD 9" > /dev/vfd
+fi
+insmod $MODDIR/stmcore-display-stx7100.ko
+   insmod $MODDIR/stmfb.ko display0=1280x720-32@50:16m::pal:rgb:rgb display1=720x576i-32@50:1m::pal:cvbs:rgb
 
-# start automounter with umount timeout of 5 seconds
-   insmod $MODDIR/autofs4.ko
-   /usr/sbin/automount --timeout=5 /autofs file /etc/auto.usb
+echo "[rcS] Loading modules"
 
-   echo "Starting DEBUG Interface"
-   /etc/init.d/mountall start
-   /etc/init.d/hostname start
+if [ ! -e /lib/firmware/audio.elf ] || [ ! -e /lib/firmware/video.elf ]; then
+   echo "[rcS] Firmware(s) missing!"
+   echo "FW MISSING!" > /dev/vfd
+   sleep 5
+fi
 
-#   echo "starting telnetd"
-#   /usr/sbin/telnetd -l /bin/autologin
+echo "[rcS] Load audio firmware (LOAD 8)"
+if [ $boxtype == 'bska' ] || [ $boxtype == 'bxzb' ]; then
+   echo "Ld 8" > /dev/vfd
+else
+   echo "LOAD 8" > /dev/vfd
+fi
+/bin/ustslave /dev/st231-1 /lib/firmware/audio.elf > /dev/null
 
-   echo "init stmfb"
-   insmod $MODDIR/stmcore-display-stx7100.ko
-   insmod $MODDIR/stmfb.ko display0=1280x720-32@50:12m:pal:yuv:yuv;# display1=720x576-16@50:1m:pal:cvbs;
+echo "[rcS] Load video firmware (LOAD 7)"
+if [ $boxtype == 'bska' ] || [ $boxtype == 'bxzb' ]; then
+   echo "Ld 7" > /dev/vfd
+else
+   echo "LOAD 7" > /dev/vfd
+fi
+/bin/ustslave /dev/st231-0 /lib/firmware/video.elf > /dev/null
 
-   echo "LOADING MODULES"
-   echo "LOADING MODULES" >/dev/vfd
+echo "[rcS] Init embx (LOAD 6)"
+if [ $boxtype == 'bska' ] || [ $boxtype == 'bxzb' ]; then
+   echo "Ld 6" > /dev/vfd
+else
+   echo "LOAD 6" > /dev/vfd
+fi
+insmod $MODDIR/embxshell.ko
+insmod $MODDIR/embxmailbox.ko mailbox0=0xb9211000:136:set2 mailbox1=0xb9212000:137:set2
+insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:1024:0xa4000000:0x10000000
+insmod $MODDIR/mme_host.ko transport0=shm
 
-   echo "init embx"
-   insmod $MODDIR/embxshell.ko
-   insmod $MODDIR/embxmailbox.ko mailbox0=0xb9211000:136:set2 mailbox1=0xb9212000:137:set2
-   insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:1024:0xa4000000:0x10000000
-   insmod $MODDIR/mme_host.ko transport0=shm
-
-   if [ $boxtype == 'bsla' ]; then
-   echo "init Cooler"
-    insmod $MODDIR/cooler.ko
-   fi
-
-   echo "init AVS"
+echo "[rcS] Init AVS (LOAD 5)"
+if [ $boxtype == 'bska' ] || [ $boxtype == 'bxzb' ]; then
+   echo "Ld 5" > /dev/vfd
+else
+   echo "LOAD 5" > /dev/vfd
+fi
+if [ $boxtype == 'bxzb' ]; then
+   insmod $MODDIR/avs.ko type=fake_avs
+else
    insmod $MODDIR/avs.ko type=stv6412
+fi
 
-   echo "init player"
-   player=`cat /proc/stb/player/version`
-   player=`cat /proc/stb/player/version | awk '{ print substr( $0, length($0) - 2, length($0) ) }'`
-   echo "init player $player"
-   insmod $MODDIR/mmelog.ko
-   insmod $MODDIR/mpeg2hw.ko mmeName=MPEG2_TRANSFORMER0
-   insmod $MODDIR/ksound.ko
-   insmod $MODDIR/p2div64.ko
-   insmod $MODDIR/stm_v4l2.ko
-    if [ $player -gt 131 ]; then
-	insmod $MODDIR/stmvout.ko
-	insmod $MODDIR/stmvbi.ko
+player=`cat /proc/stb/player/version | awk '{ print substr( $0, length($0) - 2, length($0) ) }'`
+echo "[rcS] Init player $player (LOAD 4)"
+if [ $boxtype == 'bska' ] || [ $boxtype == 'bxzb' ]; then
+   echo "Ld 4" > /dev/vfd
+else
+   echo "LOAD 4" > /dev/vfd
+fi
+insmod $MODDIR/mmelog.ko
+insmod $MODDIR/mpeg2hw.ko mmeName=MPEG2_TRANSFORMER0;
+insmod $MODDIR/ksound.ko
+insmod $MODDIR/p2div64.ko
+insmod $MODDIR/stm_v4l2.ko
+insmod $MODDIR/pseudocard.ko
+
+echo "[rcS] Init frontend(s)"
+if [ $boxtype == 'bska' ] || [ $boxtype == 'bxzb' ]; then
+   echo "[rcS] init frontends (single tuner)"
+   insmod $MODDIR/fe-core.ko
+else
+   echo "[rcS] init frontends (twin tuner)"
+   if [ $boxtype == 'bsla' ]; then
+      insmod $MODDIR/fe-core-twin1.ko
+   else
+      insmod $MODDIR/fe-core-twin2.ko paramDebug=100
    fi
-   insmod $MODDIR/pseudocard.ko
+fi
 
-    if [ $boxtype == 'bska' ]; then
-         echo "init frontends bialy"
-         insmod $MODDIR/fe-core.ko tuner=bialy ;
-    else
-         echo "init frontends czarny"
-	 insmod $MODDIR/fe-core.ko tuner=czarny ;
-    fi
+echo "[rcS] Init CI & cardreader"
+insmod $MODDIR/pti.ko waitMS=20 videoMem=4096
+if [ $? -ne 0 ]; then
    insmod $MODDIR/pti.ko
-   insmod $MODDIR/stmdvb.ko
-   insmod $MODDIR/stm_monitor.ko
-   insmod $MODDIR/player2.ko
-   insmod $MODDIR/sth264pp.ko
-   insmod $MODDIR/stmalloc.ko
-   insmod $MODDIR/platform.ko
-   insmod $MODDIR/bpamem.ko
-   insmod $MODDIR/smartcard.ko
+   echo "[rcS] Simple pti"
+else
+   echo "[rcS] Full feature pti"
+fi
+insmod $MODDIR/stm_monitor.ko
+insmod $MODDIR/stmsysfs.ko
+if [ $boxtype == 'bzzb' ]; then
+   insmod $MODDIR/stmdvb.ko TSIS_mode=serial NIMS=twin
+elif [ $boxtype == 'bsla' ]; then
+   insmod $MODDIR/stmdvb.ko TSIS_mode=parallel NIMS=twin
+else
+   insmod $MODDIR/stmdvb.ko TSIS_mode=parallel NIMS=single
+fi
 
-   /usr/local/bin/dvbtest -4 -f l /var/boot/bootlogo.mvi
+echo "[rcS] Init player2 (LOAD 3)"
+if [ $boxtype == 'bska' ] || [ $boxtype == 'bxzb' ]; then
+   echo "Ld 3" > /dev/vfd
+else
+   echo "LOAD 3" > /dev/vfd
+fi
+insmod $MODDIR/player2.ko
+insmod $MODDIR/sth264pp.ko
+insmod $MODDIR/stmalloc.ko
+insmod $MODDIR/platform.ko
 
-   echo "init frontpanel"
-   insmod $MODDIR/boxtype.ko
-   insmod $MODDIR/simu_button.ko
+insmod $MODDIR/bpamem.ko
+insmod $MODDIR/smartcard.ko
 
-   echo "init lircd"
-   mkdir -p /var/run/lirc
-   /usr/bin/lircd
+#/usr/local/bin/dvbtest -4 -f l /var/boot/bootlogo.mvi
 
-   /bin/evremote2 &
+if [ -e $MODDIR/cec_ctrl.ko ];then
+   echo "[rcS] Init HDMI-CEC"
+   insmod $MODDIR/cec_ctrl.ko
+fi
 
-# Module aus modules.extra laden
-   [ -f /var/etc/modules.extra ] && eval `sed -e 's/#.*//' -e '/^\s*$/d' -e 's/^\(.*\)/insmod \0;/' < /var/etc/modules.extra`
+if [ -e $MODDIR/exportfs.ko ]; then
+   echo "[rcS] Init exportfs"
+   insmod $MODDIR/exportfs.ko
+fi
 
-#   /etc/init.d/vsftpd start
-   /usr/sbin/inetd
+if [ -e $MODDIR/cifs.ko ]; then
+   echo "[rcS] Init CIFS support"
+   insmod $MODDIR/cifs.ko
+fi
 
-   #timefix
-   date -s "200901011200"
+if [ -e $MODDIR/ntfs.ko ]; then
+   echo "[rcS] Init NTFS support"
+   insmod $MODDIR/ntfs.ko
+fi
 
-   echo "LOADING neutrino" > /dev/vfd
-   echo "LOADING neutrino"
+if [ -e $MODDIR/tun.ko ]; then
+   echo "[rcS] Init tun support"
+   insmod $MODDIR/tun.ko
+fi
 
-   until false
-   do
-      echo "starting neutrino ->"
-      /etc/init.d/networking restart
-      /usr/bin/start-emu.sh
-      /usr/local/bin/neutrino
-      rtv=$?
-      echo "neutrino ended <- RTV: " $rtv
-      case "$rtv" in
-		0) echo "0"
-		   echo "SHUTDOWN"
-		   init 0;;
-		1) echo "1"
-		   echo "REBOOT"
-		   init 6;;
-		*) echo "*"
-		   echo "ERROR"
-		   init 6;;
+if [ -e $MODDIR/usbserial.ko ]; then
+   insmod $MODDIR/usbserial.ko
+   if [ -e $MODDIR/ch341.ko ]; then
+   echo "[rcS] Init CH341 USB serial support"
+      insmod $MODDIR/ch341.ko
+   fi
+   if [ -e $MODDIR/ftdi.ko ]; then
+      echo "[rcS] Init FTDI USB serial support"
+      insmod $MODDIR/ftdi.ko
+   fi
+   if [ -e $MODDIR/pl2303.ko ]; then
+   echo "[rcS] Init PL2303 USB serial support"
+      insmod $MODDIR/pl2303.ko
+   fi
+   if [ -e $MODDIR/option.ko ]; then
+      insmod $MODDIR/option.ko
+   fi
+   if [ -e $MODDIR/usb_wwan.ko ]; then # 3G modem
+      insmod $MODDIR/usb_wwan.ko
+   fi
+fi
+
+echo "[rcS] Init remote control (LOAD 2)"
+if [ $boxtype == 'bska' ] || [ $boxtype == 'bxzb' ]; then
+   echo "Ld 2" > /dev/vfd
+else
+   echo "LOAD 2" > /dev/vfd
+fi
+mkdir -p /var/run/lirc
+/usr/bin/lircd
+/bin/evremote2 &
+
+# OpenSSh daemon
+if [ -e /etc/init.d/sshd ]; then
+   (sleep 30; /etc/init.d/sshd start) &
+fi
+
+echo "[rcS] Load extra modules"
+# Load modules from /var/etc/modules.extra
+[ -f /var/etc/modules.extra ] && eval `sed -e 's/#.*//' -e '/^\s*$/d' -e 's/^\(.*\)/insmod \0;/' < /var/etc/modules.extra`
+
+#stfbcontrol a 255
+
+echo "[rcS] Set up wired network"
+NFS=`grep -c nfs /proc/cmdline`
+if [ "$NFS" -eq "1" ]; then
+   echo "[rcS] Booting from NFS, do not set network"
+else
+   if [ -e /etc/network/interfaces ]; then
+      ip addr flush eth0
+      /etc/init.d/networking stop
+      DHCP=`grep -c 'iface eth0 inet dhcp' /etc/network/interfaces`
+      if [ "$DHCP" -eq "1" ]; then
+         echo "[rcS] Starting DHCP"
+         /etc/init.d/udhcpc start
+      fi
+      /etc/init.d/networking start
+   fi
+fi
+
+#wlan=rtl8188cu
+if [ ! $wlan ] || [ ! -e $MODDIR/$wlan.ko ]; then
+   echo "No WLAN"
+else
+   insmod $MODDIR/$wlan.ko
+   echo "$wlan WLAN"
+#   echo "$wlan WLAN" > /dev/vfd
+#   sleep 3
+fi
+
+echo "[rcS] Do extras (LOAD 1)"
+if [ $boxtype == 'bska' ] || [ $boxtype == 'bxzb' ]; then
+   echo "Ld 1" > /dev/vfd
+else
+   echo "LOAD 1" > /dev/vfd
+fi
+# Try and synchronise time
+echo "[rcS] Set internet time"
+if [ -x /usr/sbin/ntpd ]; then
+   (ntpd -n -p 0.europe.pool.ntp.org -q; /bin/fp_control -sst)
+fi
+
+echo "[rcS] Init portmap & ftp"
+/etc/init.d/portmap start
+/etc/init.d/vsftpd start
+/usr/sbin/inetd
+
+# Do own extras
+if [ -e /etc/ownscript.sh ]; then
+   /etc/ownscript.sh &
+fi
+
+echo "[rcS] Loading Neutrino"
+if [ $boxtype == 'bska' ] || [ $boxtype == 'bxzb' ]; then
+   echo "LdNE" > /dev/vfd
+else
+   echo "Loading Neutrino" > /dev/vfd
+fi
+until false
+do
+   echo "[rcS] Starting Neutrino->"
+   /usr/bin/neutrino
+   rtv=$?
+   echo "[rcS] Neutrino ended <- return value: " $rtv
+   case "$rtv" in
+      0) echo "[rcS] SHUTDOWN"
+          if [ $boxtype == 'bska' ] || [ $boxtype == 'bxzb' ]; then
+           echo "Shdn" > /dev/vfd
+         else
+            echo "SHUTDOWN" > /dev/vfd
+         fi
+         init 0;;
+      1) echo "[rcS] REBOOT"
+         if [ $boxtype == 'bska' ] || [ $boxtype == 'bxzb' ]; then
+           echo "Rebt" > /dev/vfd
+         else
+            echo "REBOOT" > /dev/vfd
+         fi
+         init 6;;
+      3) echo "[rcS] RESTART"
+         if [ $boxtype == 'bska' ] || [ $boxtype == 'bxzb' ]; then
+           echo "ReSt" > /dev/vfd
+         else
+            echo "RESTART" > /dev/vfd
+         fi;;
+      *) echo "[rcS] Neutrino ERROR"
+         if [ $boxtype == 'bska' ] || [ $boxtype == 'bxzb' ]; then
+           echo "NeEr" > /dev/vfd
+         else
+            echo "Neutrino ERROR" > /dev/vfd
+         fi
+         init 6;;
       esac
    done
 fi
 
 #never reached
 echo "REBOOT" > /dev/vfd
-echo "REBOOT"
+echo "[rcS] REBOOT ADB_BOX"
 init 6
diff --git a/root/release/rcS_neutrino_tf7700 b/root/release/rcS_neutrino_tf7700
--- a/root/release/rcS_neutrino_tf7700
+++ b/root/release/rcS_neutrino_tf7700
@@ -1,4 +1,7 @@
 #!/bin/sh
+#Version 220711.1
+
+echo "Topfield TF77X0HDPVR Neutrino"
 
 MODDIR=/lib/modules
 
@@ -12,17 +15,23 @@ mknod -m 0666 /dev/rc      c 62 1 2>/dev/null
 mknod -m 0666 /dev/fplarge c 62 2 2>/dev/null
 mknod -m 0666 /dev/fpsmall c 62 3 2>/dev/null
 
+echo "Init frontpanel"
 insmod $MODDIR/e2_proc.ko
 insmod $MODDIR/tffp.ko
+
+insmod $MODDIR/simu_button.ko
+tffpctl --keyemulationmode 2
 
 if [ -e /var/etc/.firstboot ]; then
    echo "WAIT" > /dev/fpsmall
    echo "3 min" > /dev/fplarge
    rm /var/etc/.firstboot
    touch /dev/.devfsd
+else
+   echo "LOAD" > /dev/fplarge
+   echo "  10" > /dev/fpsmall
+   echo "LOAD 10"
 fi
-
-/etc/init.d/mountvirtfs start
 
 # remove /dev/ttyAS1 to avoid interference with the FP driver
 if [ -e /dev/ttyAS1 ]; then
@@ -32,124 +41,215 @@ fi
 # Update the GMT offset in case it changed during the standby
 /bin/tffpctl --setgmtoffset
 
+/etc/init.d/mountvirtfs start
 /etc/init.d/portmap start
-/etc/init.d/autofs start
-if [ ! -e /var/etc/.firstboot ]; then
-   echo "LOAD" > /dev/fpsmall
-   echo "MODULES" > /dev/fplarge
-   echo "LOADING MODULES"
 
-   echo "init stmfb"
-   insmod $MODDIR/stmcore-display-stx7109c3.ko
-   insmod $MODDIR/stmfb.ko display0=1280x720-32@50:12m:pal:yuv:yuv
+#/etc/init.d/autofs start
 
-   echo "load video firmware"
-   /bin/dd if=/dev/zero of=/dev/st231-0 bs=1024 count=4096
-#   /bin/stslave -t st231.0 -R /lib/firmware/video.elf
-   /bin/ustslave /dev/st231-0 /lib/firmware/video.elf
+echo -n "Starting telnetd "
+/usr/sbin/telnetd -l /bin/autologin
+echo "with autologin"
 
-   echo "load audio firmware"
-   /bin/dd if=/dev/zero of=/dev/st231-1 bs=1024 count=4096
-#   /bin/stslave -t st231.1 -R /lib/firmware/audio.elf
-   /bin/ustslave /dev/st231-1 /lib/firmware/audio.elf
+echo "Loading modules"
 
-   echo "init embx"
-   insmod $MODDIR/embxshell.ko
-   insmod $MODDIR/embxmailbox.ko mailbox0=0xb9211000:136:set2 mailbox1=0xb9212000:0
-   insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:1024:0xa4000000:0x10000000
-   insmod $MODDIR/mme_host.ko transport0=shm
+echo "LOAD" > /dev/fplarge
+echo "   9" > /dev/fpsmall
+echo "Init stmfb (LOAD 9)"
+insmod $MODDIR/stmcore-display-stx7109c3.ko
+insmod $MODDIR/stmfb.ko display0=1280x720-32@50:12m:pal:yuv:yuv
 
-   echo "init AVS"
-   insmod $MODDIR/avs.ko type=stv6412
+ if [ ! -e /lib/firmware/audio.elf ] || [ ! -e /lib/firmware/video.elf ]; then
+   echo "FIRMWARE MISSING!"
+   echo "  FW" > /dev/fpsmall
+   echo "MISSING!" > /dev/fplarge
+fi
 
-   echo "init player"
-   insmod $MODDIR/mmelog.ko
-   insmod $MODDIR/mpeg2hw.ko mmeName=MPEG2_TRANSFORMER0
-   insmod $MODDIR/ksound.ko
-   insmod $MODDIR/p2div64.ko
-   insmod $MODDIR/stm_v4l2.ko
-   insmod $MODDIR/pseudocard.ko
+echo "Load audio firmware (LOAD 8)"
+echo "   8"  > /dev/fpsmall
+/bin/dd if=/dev/zero of=/dev/st231-0 bs=1024 count=4096
+if [ -e /lib/firmware/audio_dts.elf ]; then
+   /bin/ustslave /dev/st231-1 //lib/firmware/audio_dts.elf > /dev/null
+else
+   /bin/ustslave /dev/st231-1 /lib/firmware/audio.elf > /dev/null
+fi
 
-   insmod $MODDIR/cx24116.ko
+echo "Load video firmware (LOAD 7)"
+/bin/dd if=/dev/zero of=/dev/st231-0 bs=1024 count=4096
+echo "   7"  > /dev/fpsmall
+bin/ustslave /dev/st231-0 /lib/firmware/video.elf > /dev/null
 
-   insmod $MODDIR/starci.ko
+echo "Init embx (LOAD 6)"
+echo "   6"  > /dev/fpsmall
+insmod $MODDIR/embxshell.ko
+insmod $MODDIR/embxmailbox.ko mailbox0=0xb9211000:136:set2 mailbox1=0xb9212000:0
+insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:1024:0xa4000000:0x10000000
+insmod $MODDIR/mme_host.ko transport0=shm
+
+echo "Init AVS (LOAD 5)" 
+echo "   5"  > /dev/fpsmall
+insmod $MODDIR/avs.ko type=stv6412
+
+player=`cat /proc/stb/player/version | awk '{ print substr( $0, length($0) - 2, length($0) ) }'`
+echo "Init player $player (LOAD 4)"
+echo "   4"  > /dev/fpsmall
+insmod $MODDIR/mmelog.ko
+insmod $MODDIR/mpeg2hw.ko mmeName=MPEG2_TRANSFORMER0
+insmod $MODDIR/ksound.ko
+insmod $MODDIR/p2div64.ko
+insmod $MODDIR/stm_v4l2.ko
+insmod $MODDIR/stmvout.ko
+insmod $MODDIR/stmvbi.ko
+insmod $MODDIR/pseudocard.ko
+
+insmod $MODDIR/cx24116.ko
+
+echo "[rcS] Init CI & cardreader"
+insmod $MODDIR/starci.ko
+insmod $MODDIR/pti.ko waitMS=20 videoMem=4096
+if [ $? -ne 0 ]; then
    insmod $MODDIR/pti.ko
+   echo "[rcS] Simple pti"
+else
+   echo "[rcS] Full feature pti"
+fi
+if [ $player=='player191' ]; then
    insmod $MODDIR/stm_monitor.ko
    insmod $MODDIR/stmsysfs.ko
-
    insmod $MODDIR/stmdvb.ko
-   insmod $MODDIR/player2.ko discardlateframe=0
-   insmod $MODDIR/sth264pp.ko
-   insmod $MODDIR/stmalloc.ko
-   insmod $MODDIR/platform.ko
-   insmod $MODDIR/silencegen.ko
-   insmod $MODDIR/bpamem.ko
-
-   echo "init frontpanel"
-   insmod $MODDIR/boxtype.ko
-   insmod $MODDIR/simu_button.ko
-   tffpctl --keyemulationmode 2
-   /bin/evremote2 110 10 &
-
-   #showiframe -p /var/boot/bootlogo.mvi &
-   stfbcontrol a 0
-
-   # Workaround why is jfs always not mountable?
-   # fsck.ext3 /dev/sda3 -a
-   fsck.jfs /dev/sda3 -a
-
-   /etc/init.d/mountall start
-   /etc/init.d/hostname start
-
-#   echo "starting telnetd"
-#   /usr/sbin/telnetd -l /bin/autologin
-#   /etc/init.d/vsftpd start
-   /usr/sbin/inetd
-
-   NFS=`grep -c nfs /proc/cmdline`
-   if [ "$NFS" -eq "1" ]; then
-      echo "Booting from nfs, don't set network"
-   else
-      if [ -e /etc/network/interfaces ]; then
-         ip addr flush eth0
-         /etc/init.d/networking stop
-         DHCP=`grep -c dhcp /etc/network/interfaces`
-         if [ "$DHCP" -eq "1" ]; then
-            echo "Starting dhcp"
-            /etc/init.d/udhcpc start
-         fi
-         /etc/init.d/networking start
-      fi
-   fi
-
-   echo "    " > /dev/fpsmall
-   echo "NEUTRINO" > /dev/fplarge
-   echo "LOADING Neutrino"
-
-   stfbcontrol a 255
-   until false
-   do
-      echo "starting neutrino ->"
-      /usr/local/bin/neutrino
-      rtv=$?
-      # update the GMT offset in case it changed while being turned on
-      /bin/tffpctl --setgmtoffset
-      echo "neutrino ended <- RTV: " $rtv
-      case "$rtv" in
-		0) echo "0"
-		   echo "SHUTDOWN"
-		   init 0;;
-		1) echo "1"
-		   echo "REBOOT"
-		   init 6;;
-		*) echo "*"
-		   echo "ERROR"
-		   init 6;;
-      esac
-   done
+elif [ $player=='player179' ]; then
+   insmod $MODDIR/stm_monitor.ko
+   insmod $MODDIR/stmsysfs.ko
+    insmod $MODDIR/stmdvb.ko
+else
+   insmod $MODDIR/stmdvb.ko
+   insmod $MODDIR/stm_monitor.ko
 fi
+
+echo "Init eplayer2 (LOAD 3)"
+echo "   3" > /dev/fpsmall
+insmod $MODDIR/player2.ko discardlateframe=0
+insmod $MODDIR/sth264pp.ko
+insmod $MODDIR/stmalloc.ko
+insmod $MODDIR/platform.ko
+insmod $MODDIR/silencegen.ko
+
+insmod $MODDIR/bpamem.ko
+
+stfbcontrol a 0
+
+# Workaround why is jfs always not mountable?
+#fsck.ext3 /dev/sda3 -a
+#fsck.jfs /dev/sda3 -a
+
+echo "Init remote control (LOAD 2)"
+echo "   2" > /dev/fpsmall
+insmod $MODDIR/boxtype.ko
+insmod $MODDIR/tfswitch.ko
+/bin/evremote2 110 10 &
+
+stfbcontrol a 255
+
+wlan=``
+if [ ! $wlan ] || [ ! -e $MODDIR/$wlan.ko ]; then
+   echo "No WLAN"
+else
+   insmod $MODDIR/$wlan.ko
+   echo "$wlan WLAN"
+#   echo "$wlan WLAN" > /dev/vfd
+#   sleep 3
+fi
+
+#/etc/init.d/mountall start
+
+/etc/init.d/hostname start
+
+if [ -e $MODDIR/ntfs.ko ]; then
+   insmod $MODDIR/ntfs.ko
+fi
+
+if [ -e $MODDIR/cifs.ko ]; then
+   insmod $MODDIR/cifs.ko
+fi
+
+echo "Init FTP & network (LOAD 1)"
+echo "   1" > /dev/fpsmall
+/etc/init.d/vsftpd start
+/usr/sbin/inetd
+
+NFS=`grep -c nfs /proc/cmdline`
+if [ "$NFS" -eq "1" ]; then
+   echo "Booting from nfs, don't set network"
+else
+   if [ -e /etc/network/interfaces ]; then
+      ip addr flush eth0
+      /etc/init.d/networking stop
+      DHCP=`grep -c 'iface eth0 inet dhcp' /etc/network/interfaces`
+      if [ "$DHCP" -eq "1" ]; then
+         echo "Starting DHCP on eth0"
+         /etc/init.d/udhcpc start
+      fi
+      /etc/init.d/networking start &
+   fi
+fi
+#Allow network to wake up and initialize
+sleep 2
+#Show IP address on frontpanel
+#ip=`ifconfig eth0 | sed -n '/inet addr/s/.*addr.\([^ ]*\) .*/\1/p'`
+#echo "IP $ip" > /dev/vfd
+#sleep 3
+
+# Start automount
+if [ -e /etc/init.d/automount ]; then
+   python /etc/init.d/automount &
+fi
+
+# Do own extras
+if [ -e /etc/ownscript.sh ]; then
+   /etc/ownscript.sh &
+fi
+
+# Try and synchronise time
+if [ -x /usr/sbin/ntpd ]; then
+   echo "[rcS]Set internet time"
+   (ntpd -n -p 0.europe.pool.ntp.org -q; /bin/fp_control -sst) &
+else
+  /bin/tffpctl --syncsystime &
+fi
+
+echo "Start Neutrino"
+echo "    " > /dev/fpsmall
+echo "START NEUTRINO" > /dev/fplarge
+
+until false
+do
+   echo "Starting Neutrino ->"
+   /usr/bin/neutrino
+   rtv=$?
+   # update the GMT offset in case it changed while being turned on
+   /bin/tffpctl --setgmtoffset
+   /bin/tffpctl --cleardisplay
+   echo "neutrino ended <- RTV: " $rtv
+   case "$rtv" in
+      0) echo "0"
+         echo "SHUTDOWN"
+         echo "SHUTDOWN" > /dev/fplarge
+         init 0;;
+      1) echo "1"
+         echo "REBOOT"
+         echo "REBOOT" > /dev/fplarge
+         init 6;;
+      3) echo "3"
+         echo "RESTART"
+         echo "RESTART" > /dev/fplarge
+         ;;
+      *) echo "*"
+         echo "ERROR"
+         echo "ERROR" > /dev/fplarge
+         init 6;;
+   esac
+done
 
 #never reached
 echo "REBOOT" > /dev/fplarge
-echo "REBOOT"
-init 6
+echo "REBOOT TF77X0"
+reboot -f
diff --git a/root/release/rcS_neutrino_ufs913 b/root/release/rcS_neutrino_ufs913
--- a/root/release/rcS_neutrino_ufs913
+++ b/root/release/rcS_neutrino_ufs913
@@ -1,159 +1,228 @@
 #!/bin/sh
+#Version 220711.1
+
+echo "[rcS] Start"
+echo "Kathrein UFS913 Neutrino"
 
 MODDIR=/lib/modules
 
-insmod $MODDIR/micom.ko paramDebug=0
+insmod $MODDIR/e2_proc.ko
+
+echo "[rcS] Init frontpanel"
+insmod $MODDIR/kathrein_micom.ko #paramDebug=50
+insmod $MODDIR/simu_button.ko
 
 if [ -e /var/etc/.firstboot ]; then
-   #fp_control does not work here
-   echo "WAIT 1 min" >/dev/vfd
-   echo "WAIT 1 min"
+   echo "Wait 1 minute" > /dev/vfd
+   echo "[rcS] Wait 1 minute"
    rm /var/etc/.firstboot
+   sleep 1
    touch /dev/.devfsd
+else
+   echo "LOAD 10" > /dev/vfd
+   echo "[rcS] LOAD 10"
 fi
 
 /etc/init.d/mountvirtfs start
 
-/etc/init.d/portmap start
-
-insmod $MODDIR/e2_proc.ko
+echo "[rcS] Starting DEBUG Interface"
+/etc/init.d/mountall start
+/etc/init.d/hostname start
 
 /etc/init.d/autofs start
 
-if [ ! -e /var/etc/.firstboot ]; then
+/sbin/ifconfig lo 127.0.0.1 up
 
-   echo "Starting DEBUG Interface"
-   /etc/init.d/mountall start
-   /etc/init.d/hostname start
-   /etc/init.d/networking start
+echo "[rcS] Starting telnetd"
+/usr/sbin/telnetd -l /bin/autologin
 
-  NFS=`grep -c nfs /proc/cmdline`
-  if [ "$NFS" -eq "1" ]; then
-      echo "Booting from nfs, don't set network"
-   else
-     if [ -e /etc/network/interfaces ]; then
-	 ip addr flush eth0
-	 HWADDR=`grep -E -o '[[:xdigit:]]{2}(:[[:xdigit:]]{2}){5}' /dev/mtd2`
-	 ifconfig eth0 down
-	 ifconfig eth0 hw ether $HWADDR
-#	 ifconfig eth0 up
-	 /etc/init.d/networking stop
-	 DHCP=`grep -c dhcp /etc/network/interfaces`
-	 if [ "$DHCP" -eq "1" ]; then
-	    echo "Starting dhcp"
-            /etc/init.d/udhcpc start
-	 fi
-	 /etc/init.d/networking start
-     fi
-   fi
+echo "[rcS] Init stmfb (LOAD 9)"
+echo "LOAD 9" > /dev/vfd
+insmod $MODDIR/stmcore-display-sti7105.ko
+insmod $MODDIR/stmfb.ko display0=1280x720-32@50:12m::pal:cvbs:yuv
 
-   fp_control -c
+echo "[rcS] Loading modules"
 
-   # green led on
-   #fp_control -l 2 1
-   # led brightness
-   fp_control -led 80
-
-   /sbin/ifconfig lo 127.0.0.1 up
-
-#   echo "starting telnetd"
-#   /usr/sbin/telnetd -l /bin/autologin
-
-   echo "init stmfb"
-   insmod $MODDIR/stmcore-display-sti7105.ko
-   insmod $MODDIR/stmfb.ko display0=1280x720-32@50:12m:pal:cvbs:yuv;# display1=720x576-16@50:8m:pal:cvbs;
-
-   echo "LOADING MODULES"
-   fp_control -t "LOADING MODULES"
-
-   if [ ! -e /lib/firmware/audio.elf ]; then
-      fp_control -t "FW MISSING!!!"
-   fi
-
-   echo "load video firmware"
-   /bin/dd if=/dev/zero of=/dev/st231-0 bs=1024 count=4096
-   /bin/ustslave /dev/st231-0 /lib/firmware/video.elf
-
-   echo "load audio firmware"
-   /bin/dd if=/dev/zero of=/dev/st231-1 bs=1024 count=4096
-   /bin/ustslave /dev/st231-1 /lib/firmware/audio.elf
-
-   echo "init embx"
-   insmod $MODDIR/embxshell.ko
-   insmod $MODDIR/embxmailbox.ko mailbox0=0xfe211000:136:set2 mailbox1=0xfe212000:0 ;
-   insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0x40000000:0x10000000 ;
-   insmod $MODDIR/mme_host.ko transport0=shm
-
-   echo "init AVS"
-   insmod $MODDIR/avs.ko type=stv6417
-   insmod $MODDIR/mmelog.ko
-   insmod $MODDIR/ksound.ko
-   insmod $MODDIR/p2div64.ko
-   insmod $MODDIR/stm_v4l2.ko
-   insmod $MODDIR/pseudocard.ko
-
-   insmod $MODDIR/frontend_platform.ko
-   insmod $MODDIR/socket.ko
-   insmod $MODDIR/lnbh221.ko
-   insmod $MODDIR/lnb_pio.ko
-   insmod $MODDIR/lnb_a8293.ko
-   insmod $MODDIR/avl6222.ko
-   insmod $MODDIR/ufs913_cic.ko
-
-   insmod $MODDIR/pti.ko
-   insmod $MODDIR/stm_monitor.ko
-   insmod $MODDIR/stmsysfs.ko
-   insmod $MODDIR/stmdvb.ko
-   insmod $MODDIR/player2.ko discardlateframe=0
-   insmod $MODDIR/sth264pp.ko
-   insmod $MODDIR/stmalloc.ko
-   insmod $MODDIR/platform.ko
-   insmod $MODDIR/silencegen.ko
-   insmod $MODDIR/bpamem.ko
-
-   echo "init frontpanel"
-   insmod $MODDIR/simu_button.ko
-
-   #params:
-   #period
-   #delay
-   /bin/evremote2 10 120 &
-
-# Module aus modules.extra laden
-   [ -f /var/etc/modules.extra ] && eval `sed -e 's/#.*//' -e '/^\s*$/d' -e 's/^\(.*\)/insmod \0;/' < /var/etc/modules.extra`
-
-   #timefix
-   date -s "200901011200"
-
-#   /etc/init.d/vsftpd start
-   /usr/sbin/inetd
-
-   echo "LOADING Neutrino" > /dev/vfd
-   echo "LOADING Neutrino"
-
-   stfbcontrol a 255
-
-   until false
-   do
-      echo "starting neutrino ->"
-      /usr/local/bin/neutrino
-      rtv=$?
-      echo "neutrino ended <- RTV: " $rtv
-      case "$rtv" in
-		0) echo "0"
-		   echo "SHUTDOWN"
-		   init 0;;
-		1) echo "1"
-		   echo "REBOOT"
-		   init 6;;
-		*) echo "*"
-		   echo "ERROR"
-		   init 6;;
-      esac
-   done
+if [ ! -e /lib/firmware/audio.elf ] || [ ! -e /lib/firmware/video.elf ]; then
+   echo "[rcS] Firmware(s) missing!"
+   echo "FW MISSING!" > /dev/vfd
+   sleep 5
 fi
 
+echo "[rcS] Load video firmware (LOAD 8)"
+echo "LOAD 8" > /dev/vfd
+/bin/dd if=/dev/zero of=/dev/st231-0 bs=1024 count=4096
+/bin/ustslave /dev/st231-0 /lib/firmware/video.elf > /dev/null
+
+echo "[rcS] Load audio firmware (LOAD 7)"
+echo "LOAD 7" > /dev/vfd
+/bin/dd if=/dev/zero of=/dev/st231-1 bs=1024 count=4096
+/bin/ustslave /dev/st231-1 /lib/firmware/audio.elf > /dev/null
+
+echo "[rcS] Init embx (LOAD 6)"
+echo "LOAD 6" > /dev/vfd
+insmod $MODDIR/embxshell.ko
+insmod $MODDIR/embxmailbox.ko mailbox0=0xfe211000:136:set2 mailbox1=0xfe212000:0
+insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0x40000000:0x10000000
+insmod $MODDIR/mme_host.ko transport0=shm
+
+echo "[rcS] Init AVS (LOAD 5)"
+echo "LOAD 5" > /dev/vfd
+insmod $MODDIR/avs.ko type=stv6417
+
+player=`cat /proc/stb/player/version`
+echo "[rcS] Init player $player (LOAD 4)"
+echo "LOAD 4" > /dev/vfd
+insmod $MODDIR/mmelog.ko
+insmod $MODDIR/ksound.ko
+insmod $MODDIR/p2div64.ko
+insmod $MODDIR/stm_v4l2.ko
+insmod $MODDIR/pseudocard.ko
+
+echo "[rcS] Init frontends"
+insmod $MODDIR/frontend_platform.ko
+insmod $MODDIR/socket.ko
+insmod $MODDIR/lnbh221.ko
+insmod $MODDIR/lnb_pio.ko
+insmod $MODDIR/lnb_a8293.ko
+insmod $MODDIR/avl6222.ko # paramDebug=50
+
+insmod $MODDIR/ufs913_cic.ko
+
+insmod $MODDIR/pti.ko waitMS=20 videoMem=4096
+if [ $? -ne 0 ]; then
+   insmod $MODDIR/pti.ko
+   echo "[rcS] Simple pti"
+else
+   echo "[rcS] Full feature pti"
+fi
+insmod $MODDIR/stm_monitor.ko
+insmod $MODDIR/stmsysfs.ko
+insmod $MODDIR/stmdvb.ko
+
+echo "[rcS] Init player2 (LOAD 3)"
+echo "LOAD 3" > /dev/vfd
+insmod $MODDIR/player2.ko discardlateframe=0
+insmod $MODDIR/sth264pp.ko
+insmod $MODDIR/stmalloc.ko
+insmod $MODDIR/platform.ko
+insmod $MODDIR/silencegen.ko
+
+insmod $MODDIR/bpamem.ko
+
+if [ -e $MODDIR/exportfs.ko ]; then
+   insmod $MODDIR/exportfs.ko
+fi
+if [ -e $MODDIR/cifs.ko ]; then
+   insmod $MODDIR/cifs.ko
+fi
+if [ -e $MODDIR/ntfs.ko ]; then
+   insmod $MODDIR/ntfs.ko
+fi
+if [ -e $MODDIR/tun.ko ]; then
+   insmod $MODDIR/tun.ko
+fi
+if [ -e $MODDIR/usbserial.ko ]; then
+   insmod $MODDIR/usbserial.ko
+   if [ -e $MODDIR/ftdi.ko ]; then
+      insmod $MODDIR/ftdi.ko
+   fi
+   if [ -e $MODDIR/pl2303.ko ]; then
+      insmod $MODDIR/pl2303.ko
+   fi
+   if [ -e $MODDIR/ch341.ko ]; then
+      insmod $MODDIR/ch341.ko
+   fi
+fi
+
+echo "[rcS] Init remote control (LOAD 2)"
+echo "LOAD 2" > /dev/vfd
+/bin/evremote2 10 120 &
+
+# Load module(s) from modules.extra
+[ -f /var/etc/modules.extra ] && eval `sed -e 's/#.*//' -e '/^\s*$/d' -e 's/^\(.*\)/insmod \0;/' < /var/etc/modules.extra`
+
+NFS=`grep -c nfs /proc/cmdline`
+if [ "$NFS" -eq "1" ]; then
+   echo "[rcS] Booting from NFS, do not set network"
+else
+   if [ -e /etc/network/interfaces ]; then
+      ip addr flush eth0
+      HWADDR=`grep -E -o '[[:xdigit:]]{2}(:[[:xdigit:]]{2}){5}' /dev/mtd2`
+      ifconfig eth0 down
+      ifconfig eth0 hw ether $HWADDR
+      /etc/init.d/networking stop
+      DHCP=`grep -c 'iface eth0 inet dhcp' /etc/network/interfaces`
+      if [ "$DHCP" -eq "1" ]; then
+         echo "[rcS] Starting DHCP"
+         /etc/init.d/udhcpc start
+      fi
+      /etc/init.d/networking start
+   fi
+fi
+
+echo -n "[rcS] Init WLAN: "
+wlan=
+if [ ! $wlan ] || [ ! -e $MODDIR/$wlan.ko ]; then
+   echo "None."
+else
+   insmod $MODDIR/$wlan.ko
+   echo "[rcS] $wlan WLAN"
+#   echo "$wlan WLAN" > /dev/vfd
+#   sleep 3
+fi
+
+echo "[rcS] Try and synchronise time (LOAD 1)"
+echo "LOAD 1" > /dev/vfd
+if [ -x /usr/sbin/ntpd ]; then
+   echo "[rcS] Set internet time"
+   (ntpd -n -p 0.europe.pool.ntp.org -q; /bin/fp_control -sst) &
+#else
+#   if [ -e /usr/sbin/time.sh ]; then
+#      echo "[rcS] Use transponder time"
+#      /usr/sbin/time.sh &
+#   fi
+fi
+
+echo "[rcS] Init portmap & ftp"
+/etc/init.d/portmap start
+/etc/init.d/vsftpd start
+/usr/sbin/inetd
+
+# Do own extras
+if [ -e /var/etc/ownscript.sh ]; then
+   /var/etc/ownscript.sh &
+fi
+
+echo "LOAD Neutrino" > /dev/vfd
+echo "[rcS] Loading Neutrino"
+
+stfbcontrol a 255
+
+until false
+do
+   echo "[rcS] Starting Neutrino ->"
+   /usr/bin/neutrino
+   rtv=$?
+   echo "Neutrino ended <- RTV: " $rtv
+   fp_control -i 17 0  # all icons off
+   case "$rtv" in
+      0) echo "[rcS] SHUTDOWN"
+         echo "Shutdown" > /dev/vfd
+         init 0;;
+      1) echo "[rcS] REBOOT"
+         echo "Reboot" > /dev/vfd
+         init 6;;
+      3) echo "[rcS] RESTART"
+         echo "Neutrino Restart" > /dev/vfd
+         ;;
+      *) echo "[rcS] ERROR"
+         echo "Error" > /dev/vfd
+         init 6;;
+   esac
+done
+
 #never reached
-echo "REBOOT UFS913" > /dev/vfd
-echo "REBOOT UFS913"
-init 6
+echo "[rcS] REBOOT UFS913"
+echo "REBOOT" > /dev/vfd
+reboot -f
