Add cdk_new features, update patches

diff --git a/root/release/rcS_enigma2_atevio7500 b/root/release/rcS_enigma2_atevio7500
--- a/root/release/rcS_enigma2_atevio7500
+++ b/root/release/rcS_enigma2_atevio7500
@@ -1,188 +1,320 @@
 #!/bin/sh
+#Version 170422.1
+
+echo "Fortis HS8200 Enigma2"
 
 MODDIR=/lib/modules
+
+insmod $MODDIR/e2_proc.ko
+
+echo "[rcS] Init frontpanel"
 insmod $MODDIR/nuvoton.ko
+insmod $MODDIR/simu_button.ko
 
 if [ -e /var/etc/.firstboot ]; then
-   #fp_control does not work here
-   echo "WAIT 1 min" >/dev/vfd
-   echo "WAIT 1 min"
+   echo "Wait 1 min." > /dev/vfd
+   echo "[rcS] WAIT 1 minute"
    rm /var/etc/.firstboot
+   sleep 1
    touch /dev/.devfsd
+else
+   echo "LOAD 10" > /dev/vfd
+   echo "[rcS] LOAD 10"
 fi
 
 /etc/init.d/mountvirtfs start
 
-/etc/init.d/portmap start
+#insmod $MODDIR/sata.ko
 
-insmod $MODDIR/e2_proc.ko
-
+# Start automounter with umount timeout of 5 seconds
+echo "[rcS] Starting automounter"
 /etc/init.d/autofs start
 
-if [ ! -e /var/etc/.firstboot ]; then
+echo "[rcS] Starting DEBUG Interface"
+/etc/init.d/mountall start
+/etc/init.d/hostname start
 
-   echo "Starting DEBUG Interface"
-   /etc/init.d/mountall start
-   /etc/init.d/hostname start
+#if [ -d /dev/sda1/Recordings ]; then
+#   echo "[rcS] Recordings directory found on /dev/sda1, checking..."
+#   fsck.jfs -a /dev/sda1
+#fi
 
-   fp_control -c
-
-   echo "starting telnetd"
+echo -n "[rcS] Starting telnetd "
+autologin=`cat /etc/enigma2/settings | grep systemoptions.autologin | cut -d "=" -f2`
+if [ ! $autologin ]; then
    /usr/sbin/telnetd -l /bin/autologin
-
-   echo "init stmfb"
-   insmod $MODDIR/stmcore-display-sti7105.ko
-   insmod $MODDIR/stmfb.ko display0=1280x720-32@50:15m:pal:yuv:yuv;# display1=720x576-16@50:1m:pal:cvbs;
-
-   echo "LOADING MODULES"   
-   fp_control -t "LOADING MODULES"
-
-   if [ ! -e /boot/audio.elf ]; then
-      fp_control -t "FW MISSING!!!"
-   fi
-
-   echo "load a firmware"
-   /bin/ustslave /dev/st231-1 /boot/audio.elf
-   echo "load v firmware"
-   /bin/ustslave /dev/st231-0 /boot/video.elf
-
-   echo "init embx"
-   insmod $MODDIR/embxshell.ko
-   insmod $MODDIR/embxmailbox.ko mailbox0=0xfe211000:136:set2 mailbox1=0xfe212000:0 ;
-   insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0x40000000:0x10000000 ;
-   insmod $MODDIR/mme_host.ko transport0=shm
-
-   echo "init AVS"
-   insmod $MODDIR/avs.ko type=stv6418
-
-   player=`cat /proc/stb/player/version`
-   if [ $player=='player191' ]; then
-      echo "init player 191"
-   elif [ $player=='player179' ]; then
-      echo "init player 179"
-   else
-      echo "init player 131"
-   fi
-   insmod $MODDIR/mmelog.ko
-   insmod $MODDIR/ksound.ko
-   insmod $MODDIR/p2div64.ko
-   insmod $MODDIR/stm_v4l2.ko
-   insmod $MODDIR/pseudocard.ko
-
-   insmod $MODDIR/frontend_platform.ko
-   insmod $MODDIR/socket.ko
-   insmod $MODDIR/lnbh221.ko
-   insmod $MODDIR/lnb_pio.ko
-   insmod $MODDIR/avl2108.ko
-#   insmod $MODDIR/tda10024.ko
-
-   insmod $MODDIR/starci.ko 
-   if [ $player=='player191' ]; then
-      # Full feature pti
-      insmod $MODDIR/pti.ko waitMS=20 videoMem=4096
-      if [ $?=='2' ]; then
-         # Simple pti
-         insmod $MODDIR/pti.ko
-      fi
-      insmod $MODDIR/stm_monitor.ko
-      insmod $MODDIR/stmsysfs.ko
-      insmod $MODDIR/stmdvb.ko
-   elif [ $player=='player179' ]; then
-      # Full feature pti
-      insmod $MODDIR/pti.ko waitMS=20 videoMem=4096
-      if [ $?=='2' ]; then
-         # Simple pti
-         insmod $MODDIR/pti.ko
-      fi
-      insmod $MODDIR/stm_monitor.ko
-      insmod $MODDIR/stmsysfs.ko
-      insmod $MODDIR/stmdvb.ko
-   else
-      insmod $MODDIR/pti.ko
-      insmod $MODDIR/stmdvb.ko
-      insmod $MODDIR/stm_monitor.ko
-   fi
-   insmod $MODDIR/player2.ko
-   insmod $MODDIR/sth264pp.ko
-   insmod $MODDIR/stmalloc.ko
-   insmod $MODDIR/platform.ko
-   insmod $MODDIR/silencegen.ko
-
-   insmod $MODDIR/bpamem.ko
-   mknod /dev/bpamem c 153 0 
-
-   showiframe -p /var/boot/bootlogo.mvi &
-   stfbcontrol a 0
-
-   echo "init frontpanel"
-   insmod $MODDIR/simu_button.ko
-
-   mknod /dev/rc c 147 1 
-
-   #params:
-   #period
-   #delay
-   /bin/evremote2 10 120 &
-
-   # timefix e2
-   # date -s "121220001970"
-
-   stfbcontrol a 255
-
-   /etc/init.d/mountall start
-
-   /etc/init.d/hostname start
-
-   echo "starting telnetd"
-   /usr/sbin/telnetd -l /bin/autologin
-   /etc/init.d/vsftpd start
-   /usr/sbin/inetd
-
-   NFS=`grep -c nfs /proc/cmdline`
-   if [ "$NFS" -eq "1" ]; then 
-      echo "Booting from nfs, don't set network" 
-   else 
-      if [ -e /etc/network/interfaces ]; then 
-	 ip addr flush eth0 
-	 /etc/init.d/networking stop 
-	 DHCP=`grep -c dhcp /etc/network/interfaces`
-	 if [ "$DHCP" -eq "1" ]; then 
-	    echo "Starting dhcp"
-            /etc/init.d/udhcpc start 
-	 fi 
-	 /etc/init.d/networking start 
-      fi 
-   fi
-
-   echo "LOADING e2" > /dev/vfd
-   echo "LOADING e2"
-
-   until false
-   do
-      echo "starting e2->"
-      /usr/local/bin/enigma2
-      rtv=$?
-      echo "e2 ended <- RTV: " $rtv
-      case "$rtv" in
-		0) echo "0"
-		   echo "E2 ERROR"
-      	   init 6;;
-		1) echo "1"
-		   echo "SHUTDOWN"
-		   init 0;;
-		2) echo "2"
-		   echo "REBOOT"
-		   init 6;;
-		3) echo "3"
-		   echo "E2 RESTART"
-		   echo "0" > /proc/progress
-		   showiframe -p /var/boot/bootlogo.mvi &;;
-		*) echo "*"
-		   echo "ERROR"
-           init 6;;
-      esac
-   done 
+   echo "with autologin"
+else
+   /usr/sbin/telnetd -l /bin/login
+   echo "with normal login"
 fi
 
-#never reached
+echo "[rcS] Init stmfb (LOAD 9)"
+echo "LOAD 9" > /dev/vfd
+insmod $MODDIR/stmcore-display-sti7105.ko
 
+if grep -q "config.av.videoport=Scart" /etc/enigma2/settings; then
+   insmod $MODDIR/stmfb.ko display0=720x576i-32@50:1m:pal:rgb:rgb #SCART
+else
+   insmod $MODDIR/stmfb.ko display0=1280x720-32@50:12m:pal:rgb:rgb #HDMI
+fi
+
+echo "[rcS] Loading modules"
+
+if [ ! -e /boot/audio.elf ] || [ ! -e /boot/video.elf ]; then
+   echo "[rcS] Firmware(s) missing!"
+   echo "FW MISSING!" > /dev/vfd
+   sleep 5
+fi
+
+echo "[rcS] Load audio firmware (LOAD 8)"
+echo "LOAD 8" > /dev/vfd
+dtsdown=`cat /etc/enigma2/settings | grep systemoptions.dtsdownmix | cut -d "=" -f2`
+if [ ! $dtsdown ] && [ -e /boot/audio_dts.elf ]; then
+   /bin/ustslave /dev/st231-1 /boot/audio_dts.elf > /dev/null
+else
+   /bin/ustslave /dev/st231-1 /boot/audio.elf > /dev/null
+fi
+
+echo "[rcS] Load video firmware (LOAD 7)"
+echo "LOAD 7" > /dev/vfd
+/bin/ustslave /dev/st231-0 /boot/video.elf > /dev/null
+
+echo "[rcS] Init embx (LOAD 6)"
+echo "LOAD 6" > /dev/vfd
+insmod $MODDIR/embxshell.ko
+insmod $MODDIR/embxmailbox.ko mailbox0=0xfe211000:136:set2 mailbox1=0xfe212000:0
+insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0x40000000:0x10000000
+insmod $MODDIR/mme_host.ko transport0=shm
+
+echo "[rcS] Init AVS (LOAD 5)"
+echo "LOAD 5" > /dev/vfd
+insmod $MODDIR/avs.ko type=stv6412
+
+player=`cat /proc/stb/player/version | awk '{ print substr( $0, length($0) - 2, length($0) ) }'`
+echo "[rcS] Init player $player (LOAD 4)"
+echo "LOAD 4" > /dev/vfd
+insmod $MODDIR/mmelog.ko
+insmod $MODDIR/ksound.ko
+insmod $MODDIR/p2div64.ko
+insmod $MODDIR/stm_v4l2.ko
+insmod $MODDIR/pseudocard.ko
+
+echo "[rcS] Init frontends"
+insmod $MODDIR/frontend_platform.ko
+insmod $MODDIR/socket.ko
+insmod $MODDIR/lnbh221.ko
+insmod $MODDIR/lnb_pio.ko
+# DVB-S
+insmod $MODDIR/avl2108.ko
+# DVB-C
+#insmod $MODDIR/tda10024.ko
+# DVB-T
+#insmod $MODDIR/cxd2820.ko
+
+echo "[rcS] Init CI & cardreader"
+insmod $MODDIR/starci.ko
+insmod $MODDIR/pti.ko waitMS=20 videoMem=4096
+if [ $?=='2' ]; then
+   insmod $MODDIR/pti.ko
+   echo "[rcS] Simple pti"
+else
+   echo "[rcS] Full feature pti"
+fi
+insmod $MODDIR/stm_monitor.ko
+insmod $MODDIR/stmsysfs.ko
+insmod $MODDIR/stmdvb.ko
+
+echo "[rcS] Init player2 (LOAD 3)"
+echo "LOAD 3" > /dev/vfd
+insmod $MODDIR/player2.ko
+insmod $MODDIR/sth264pp.ko
+insmod $MODDIR/stmalloc.ko
+insmod $MODDIR/platform.ko
+insmod $MODDIR/silencegen.ko
+
+insmod $MODDIR/bpamem.ko
+mknod /dev/bpamem c 153 0
+
+if [ -e /boot/bootlogo.mvi ]; then
+   showiframe -p /boot/bootlogo.mvi &
+fi
+
+stfbcontrol a 0
+
+if [ -e $MODDIR/cec.ko ];then
+   echo "[rcS] Init HDMI-CEC"
+   insmod $MODDIR/cec.ko activemode=1
+fi
+
+if [ -e $MODDIR/exportfs.ko ]; then
+   echo "[rcS] Init exportfs"
+   insmod $MODDIR/exportfs.ko
+fi
+
+if [ -e $MODDIR/cifs.ko ]; then
+echo "[rcS] Init CIFS support"
+   insmod $MODDIR/cifs.ko
+fi
+
+if [ -e $MODDIR/ntfs.ko ]; then
+   echo "[rcS] Init NTFS support"
+   insmod $MODDIR/ntfs.ko
+fi
+
+if [ -e $MODDIR/tun.ko ]; then
+echo "[rcS] Init tun support"
+   insmod $MODDIR/tun.ko
+fi
+
+if [ -e $MODDIR/usbserial.ko ]; then
+   insmod $MODDIR/usbserial.ko
+   if [ -e $MODDIR/ftdi.ko ]; then
+   echo "[rcS] Init FTDI USB serial support"
+      insmod $MODDIR/ftdi.ko
+   fi
+   if [ -e $MODDIR/pl2303.ko ]; then
+   echo "[rcS] Init PL2303 USB serial support"
+      insmod $MODDIR/pl2303.ko
+   fi
+fi
+
+echo "[rcS] Init remote control (LOAD 2)"
+echo "LOAD 2" > /dev/vfd
+mknod /dev/rc c 147 1
+/bin/evremote2 10 140 &
+
+stfbcontrol a 255
+
+NFS=`grep -c nfs /proc/cmdline`
+if [ "$NFS" -eq "1" ]; then
+   echo "[rcS] Booting from NFS, don't set network"
+else
+   if [ -e /etc/network/interfaces ]; then
+      ip addr flush eth0
+      /etc/init.d/networking stop
+      DHCP=`grep -c 'iface eth0 inet dhcp' /etc/network/interfaces`
+      if [ "$DHCP" -eq "1" ]; then
+         echo "[rcS] Starting DHCP"
+         /etc/init.d/udhcpc start
+      fi
+      /etc/init.d/networking start
+   fi
+fi
+#Allow network to wake up and initialize
+sleep 2
+#Show IP address on frontpanel
+#ip=`ifconfig eth0 | sed -n '/inet addr/s/.*addr.\([^ ]*\) .*/\1/p'`
+#echo "IP $ip" > /dev/vfd
+#sleep 3
+
+echo -n "[rcS] Init WLAN: "
+wlan=`cat /etc/enigma2/settings | grep systemoptions.wlan | cut -d "=" -f2`
+if [ ! $wlan ] || [ ! -e $MODDIR/$wlan.ko ]; then
+   echo "None."
+else
+   insmod $MODDIR/$wlan.ko
+   echo "$wlan"
+#   echo "$wlan WLAN" > /dev/vfd
+#   sleep 3
+fi
+
+# Handle SWAPPART and RECORD labels and USB devices
+if [ -e /usr/sbin/amount.sh ]; then
+   (sleep 20; /usr/sbin/amount.sh) &
+fi
+
+# inadyn
+inadyn=`cat /etc/enigma2/settings | grep systemoptions.inadyn | cut -d "=" -f2`
+if [ ! $inadyn ] ||  [ ! -e /usr/bin/inadyn ]; then
+   echo "[rcS] No inadyn"
+else
+   if [ -e /usr/bin/inadyn ]; then
+      /usr/bin/inadyn &
+   fi
+fi
+
+# OpenSSh daemon
+openssh=`cat /etc/enigma2/settings | grep systemoptions.openssh | cut -d "=" -f2`
+if [ ! $openssh ] || [ ! -e /etc/init.d/sshd ]; then
+   echo "[rcS] No OpenSSH"
+else
+   if [ -e /etc/init.d/sshd ]; then
+      (sleep 30; /etc/init.d/sshd start) &
+   fi
+fi
+
+# Enable PKT plugins
+if [ ! -e /tmp/reference.dat ] && [ -e /var/bin/reference.dat ]; then
+   cp /var/bin/reference.dat /tmp
+fi
+
+# Try and synchronise time
+#inettime=`cat /etc/enigma2/settings | grep systemoptions.inettime | cut -d "=" -f2`
+# if [ ! $inettime ] && [ -e /sbin/ntpdate ]; then
+if [ -e /sbin/ntpdate ]; then
+   echo "[rcS] Set internet time"
+   (/sbin/ntpdate nl.pool.ntp.org; /bin/fp_control -sst) &
+else
+   if [ -e /usr/sbin/time.sh ]; then
+      echo "[rcS] Use transponder time"
+      /usr/sbin/time.sh &
+   fi
+fi
+
+echo "[rcS] Init portmap & ftp (LOAD 1)"
+echo "LOAD 1" > /dev/vfd
+/etc/init.d/portmap start
+/etc/init.d/vsftpd start
+/usr/sbin/inetd
+
+# Do own extras
+if [ -e /etc/ownscript.sh ]; then
+   /etc/ownscript.sh &
+fi
+
+echo "Loading E2" > /dev/vfd
+echo "[rcS] Loading E2"
+
+until false
+do
+   echo "[rcS] Entering e2 main loop"
+   if [ -e /usr/local/share/enigma2/backdrop.mvi ]; then
+      showiframe -p /usr/local/share/enigma2/backdrop.mvi &
+   fi
+   /usr/local/bin/enigma2
+   rtv=$?
+   echo "[rcS] e2 ended <- return value: " $rtv
+   fp_control -i 23 0
+   case "$rtv" in
+      0) echo "E2 ERROR"
+         echo "E2 Error" > /dev/vfd
+         init 6;;
+      1) echo "SHUTDOWN"
+         echo "Shutdown" > /dev/vfd
+         if [ -e /usr/local/share/enigma2/shutdown.mvi ]; then
+            showiframe -p /usr/local/share/enigma2/shutdown.mvi &
+         fi
+         init 0;;
+      2) echo "REBOOT"
+         echo "Reboot" > /dev/vfd
+         init 6;;
+      3) echo "E2 RESTART"
+         echo "Restart GUI" > /dev/vfd
+         echo "0" > /proc/progress
+         if [ -e /usr/local/share/enigma2/backdrop.mvi ]; then
+            showiframe -p /usr/local/share/enigma2/backdrop.mvi &
+         else
+            showiframe -p /boot/bootlogo.mvi &
+         fi
+         echo -n " ";;
+      *) echo "ERROR"
+         echo "Error" > /dev/vfd
+         init 6;;
+   esac
+done
+
+#never reached
+echo "REBOOT HS8200" > /dev/vfd
+echo "REBOOT HS8200"
+reboot -f
diff --git a/root/release/rcS_enigma2_fortis_hdbox b/root/release/rcS_enigma2_fortis_hdbox
--- a/root/release/rcS_enigma2_fortis_hdbox
+++ b/root/release/rcS_enigma2_fortis_hdbox
@@ -1,167 +1,293 @@
 #!/bin/sh
+#Version 170422.1
 
-echo "[rcS] start"
+echo "Fortis FS9000/9200 Enigma2"
+
 MODDIR=/lib/modules
 
+insmod $MODDIR/e2_proc.ko
+
+echo "[rcS] Init frontpanel"
 if [ ! -e /dev/vfd ]; then
-    mknod -m 0660 /dev/vfd c 147 0
+   mknod -m 0660 /dev/vfd c 147 0
 fi
 insmod $MODDIR/nuvoton.ko
 
 if [ -e /var/etc/.firstboot ]; then
-   echo "WAIT 1 min" > /dev/vfd
-   echo "WAIT 1 min"
+   echo "Wait 1 min." > /dev/vfd
+   echo "[rcS] WAIT 1 minute"
    rm /var/etc/.firstboot
+   sleep 1
    touch /dev/.devfsd
+else
+   echo "LOAD 10" > /dev/vfd
+   echo "[rcS] LOAD 10"
 fi
 
 /etc/init.d/mountvirtfs start
 
-insmod $MODDIR/e2_proc.ko
+echo "[rcS] Starting DEBUG Interface"
+/etc/init.d/mountall start
+/etc/init.d/hostname start
 
-if [ ! -e /var/etc/.firstboot ]; then
+#if [ -d /dev/sda1/Recordings ]; then
+#   echo "[rcS] Recordings directory found on /dev/sda1, checking..."
+#   fsck.jfs -a /dev/sda1
+#fi
 
-   echo "Starting DEBUG Interface"
-   /etc/init.d/mountall start
-   /etc/init.d/hostname start
-
-   echo "starting telnetd"
+echo -n "[rcS] Starting telnetd "
+autologin=`cat /etc/enigma2/settings | grep systemoptions.autologin | cut -d "=" -f2`
+if [ ! $autologin ]; then
    /usr/sbin/telnetd -l /bin/autologin
-
-   echo "init stmfb"
-   insmod $MODDIR/stmcore-display-stx7109c3.ko
-   insmod $MODDIR/stmfb.ko display0=720x576-32@50:15m:pal:yuv:yuv
-  
-   echo "STB7100-VIDEO"
-   /bin/ustslave /dev/st231-0 /boot/video.elf
-   echo "STB7100-AUDIO"
-   /bin/ustslave /dev/st231-1 /boot/audio.elf
-
-   echo "LOADING MODULES"
-   echo "LOADING MODULES" >/dev/vfd
-
-   echo "init embx"
-   insmod $MODDIR/embxshell.ko
-   insmod $MODDIR/embxmailbox.ko mailbox0=0xb9211000:136:set2 mailbox1=0xb9212000:0 ;
-   insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:1024:0xa4000000:0x10000000 ;
-   insmod $MODDIR/mme_host.ko transport0=shm
-
-   echo "init AVS"
-   insmod $MODDIR/avs.ko type=stv6412
-
-   player=`cat /proc/stb/player/version`
-   if [ $player=='player179' ]; then
-      echo "init player 179"
-   elif [ $player=='player191' ]; then
-      echo "init player 191"
-   else
-      echo "init player 131"
-   fi
-
-   echo "init player"
-   insmod $MODDIR/mmelog.ko
-   insmod $MODDIR/mpeg2hw.ko mmeName=MPEG2_TRANSFORMER1;
-   insmod $MODDIR/ksound.ko
-   insmod $MODDIR/p2div64.ko
-   insmod $MODDIR/stm_v4l2.ko
-   insmod $MODDIR/pseudocard.ko
-
-   insmod $MODDIR/stv090x.ko
-   insmod $MODDIR/starci.ko
-
-   if [ $player=='player179' ]; then
-      # Full feature pti
-      insmod $MODDIR/pti.ko waitMS=20 videoMem=4096
-      if [ $?=='2' ]; then
-         # Simple pti
-         insmod $MODDIR/pti.ko
-      fi
-      insmod $MODDIR/stm_monitor.ko
-      insmod $MODDIR/stmsysfs.ko
-      insmod $MODDIR/stmdvb.ko
-   elif [ $player=='player191' ]; then
-      # Full feature pti
-      insmod $MODDIR/pti.ko waitMS=20 videoMem=4096
-      if [ $?=='2' ]; then
-         # Simple pti
-         insmod $MODDIR/pti.ko
-      fi
-      insmod $MODDIR/stm_monitor.ko
-      insmod $MODDIR/stmsysfs.ko
-      insmod $MODDIR/stmdvb.ko
-   else
-      insmod $MODDIR/pti.ko
-      insmod $MODDIR/stmdvb.ko
-      insmod $MODDIR/stm_monitor.ko
-   fi
-
-   insmod $MODDIR/player2.ko noaudiosync=1; discardlateframe=0; useoldaudiofw=1 ;
-   insmod $MODDIR/sth264pp.ko
-   insmod $MODDIR/stmalloc.ko
-   insmod $MODDIR/platform.ko
-
-  # insmod $MODDIR/cifs.ko
-
-   echo "init frontpanel"
-   insmod $MODDIR/boxtype.ko
-   insmod $MODDIR/simu_button.ko
-
-   mknod /dev/rc c 147 1
-
-   #params:
-   #period
-   #delay
-   /bin/evremote2 10 140 &
-
-   echo "init cardreader"
-   mknod /dev/sci0 c 253 0
-   mknod /dev/sci1 c 253 1
-#	insmod $MODDIR/sci-ng.ko
-
-   #DVD-PLAYER EXIT-TASTE LOAD OR EJECT DVD
-   #mount /dev/sr0 /media/dvd
-   #fix this later if we got to manage a marusys raw device driver
-
-   /etc/init.d/portmap start
-   /etc/init.d/vsftpd start
-   /usr/sbin/inetd
-
-   #timefix e2
-   date -s "200901011200"
-
-#   stfbcontrol a 255
-
-   echo "LOADING e2" > /dev/vfd
-   echo "LOADING e2"
-
-   until false
-   do
-      echo "starting e2->"
-      /usr/local/bin/enigma2
-      rtv=$?
-      echo "e2 ended <- RTV: " $rtv
-      case "$rtv" in
-		0) echo "0"
-		   echo "E2 ERROR"
-      	   init 6;;
-		1) echo "1"
-		   echo "SHUTDOWN"
-		   init 0;;
-		2) echo "2"
-		   echo "REBOOT"
-		   init 6;;
-		3) echo "3"
-		   echo "E2 RESTART"
-		   echo "0" > /proc/progress
-		   showiframe -p /var/boot/bootlogo.mvi &;;
-		*) echo "*"
-		   echo "ERROR"
-           init 6;;
-      esac
-   done
+   echo "with autologin"
+else
+   /usr/sbin/telnetd -l /bin/login
+   echo "with normal login"
 fi
 
+echo "[rcS] Init stmfb (LOAD 9)"
+echo "LOAD 9" > /dev/vfd
+insmod $MODDIR/stmcore-display-stx7109c3.ko
+if grep -q "config.av.videoport=Scart" /etc/enigma2/settings; then
+  insmod $MODDIR/stmfb.ko display0=720x576-32@50:15m:pal:rgb:rgb #SCART
+else
+  insmod $MODDIR/stmfb.ko display0=1280x720-32@50:16m:pal:rgb:rgb; #HDMI
+fi
+
+echo "[rcS] Loading modules"
+
+if [ ! -e /boot/audio.elf ] || [ ! -e /boot/video.elf ]; then
+   echo "[rcS] Firmware(s) missing!"
+   echo "FW MISSING!" > /dev/vfd
+   sleep 5
+fi
+
+echo "[rcS] Load audio firmware (LOAD 8)"
+echo "LOAD 8" > /dev/vfd
+/bin/ustslave /dev/st231-1 /boot/audio.elf > /dev/null
+
+echo "[rcS] Load video firmware (LOAD 7)"
+echo "LOAD 7" > /dev/vfd
+/bin/ustslave /dev/st231-0 /boot/video.elf > /dev/null
+
+echo "[rcS] Init embx (LOAD 6)"
+echo "LOAD 6" > /dev/vfd
+insmod $MODDIR/embxshell.ko
+insmod $MODDIR/embxmailbox.ko mailbox0=0xb9211000:136:set2 mailbox1=0xb9212000:0
+insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:1024:0xa4000000:0x10000000
+insmod $MODDIR/mme_host.ko transport0=shm
+
+echo "[rcS] Init AVS (LOAD 5)"
+echo "LOAD 5" > /dev/vfd
+insmod $MODDIR/avs.ko type=stv6412
+
+player=`cat /proc/stb/player/version | awk '{ print substr( $0, length($0) - 2, length($0) ) }'`
+echo "[rcS] Init player $player (LOAD 4)"
+echo "LOAD 4" > /dev/vfd
+insmod $MODDIR/mmelog.ko
+insmod $MODDIR/mpeg2hw.ko mmeName=MPEG2_TRANSFORMER1;
+insmod $MODDIR/stmsysfs.ko
+insmod $MODDIR/ksound.ko
+insmod $MODDIR/p2div64.ko
+insmod $MODDIR/stm_v4l2.ko
+insmod $MODDIR/pseudocard.ko
+
+echo "[rcS] Init frontends"
+insmod $MODDIR/stv090x.ko
+echo "[rcS] Init CI & cardreader"
+insmod $MODDIR/starci.ko
+
+insmod $MODDIR/pti.ko waitMS=20 videoMem=4096
+if [ $?=='2' ]; then
+   insmod $MODDIR/pti.ko
+   echo "[rcS] Simple pti"
+else
+   echo "[rcS] Full feature pti"
+fi
+insmod $MODDIR/stm_monitor.ko
+insmod $MODDIR/stmdvb.ko
+
+echo "[rcS] Init player2 (LOAD 3)"
+echo "LOAD 3" > /dev/vfd
+insmod $MODDIR/player2.ko noaudiosync=1; discardlateframe=0; useoldaudiofw=1;
+insmod $MODDIR/sth264pp.ko
+insmod $MODDIR/stmalloc.ko
+insmod $MODDIR/platform.ko
+
+if [ -e /boot/bootlogo.mvi ]; then
+   showiframe -p /boot/bootlogo.mvi &
+fi
+
+if [ -e $MODDIR/exportfs.ko ]; then
+   insmod $MODDIR/exportfs.ko
+fi
+if [ -e $MODDIR/cifs.ko ]; then
+   insmod $MODDIR/cifs.ko
+fi
+if [ -e $MODDIR/ntfs.ko ]; then
+   insmod $MODDIR/ntfs.ko
+fi
+if [ -e $MODDIR/tun.ko ]; then
+   insmod $MODDIR/tun.ko
+fi
+if [ -e $MODDIR/usbserial.ko ]; then
+   insmod $MODDIR/usbserial.ko
+fi
+if [ -e $MODDIR/ftdi.ko ]; then
+   insmod $MODDIR/ftdi.ko
+fi
+if [ -e $MODDIR/pl2303.ko ]; then
+   insmod $MODDIR/pl2303.ko
+fi
+
+echo "[rcS] Init frontpanel (LOAD 2)"
+echo "LOAD 2" > /dev/vfd
+insmod $MODDIR/boxtype.ko
+insmod $MODDIR/simu_button.ko
+
+echo "[rcS] Init remote control"
+echo "Load 2" > /dev/vfd
+mknod /dev/rc c 147 1
+/bin/evremote2 10 140 &
+
+echo "[rcS] Init smartcard cardreader"
+mknod /dev/sci0 c 253 0
+mknod /dev/sci1 c 253 1
+#insmod $MODDIR/sci-ng.ko
+
+NFS=`grep -c nfs /proc/cmdline`
+if [ "$NFS" -eq "1" ]; then
+   echo "[rcS] Booting from nfs, don't set network"
+else
+   if [ -e /etc/network/interfaces ]; then
+      ip addr flush eth0
+      /etc/init.d/networking stop
+      DHCP=`grep -c 'iface eth0 inet dhcp' /etc/network/interfaces`
+      if [ "$DHCP" -eq "1" ]; then
+         echo "[rcS] Starting DHCP"
+         /etc/init.d/udhcpc start
+      fi
+      /etc/init.d/networking start
+   fi
+fi
+#Allow network to wake up and initialize
+sleep 2
+#Show IP address on frontpanel
+#ip=`ifconfig eth0 | sed -n '/inet addr/s/.*addr.\([^ ]*\) .*/\1/p'`
+#echo "IP $ip" > /dev/vfd
+#sleep 3
+
+echo -n "[rcS] Init WLAN: "
+wlan=`cat /etc/enigma2/settings | grep systemoptions.wlan | cut -d "=" -f2`
+if [ ! $wlan ] || [ ! -e $MODDIR/$wlan.ko ]; then
+   echo "None."
+else
+   insmod $MODDIR/$wlan.ko
+   echo "[rcS] $wlan WLAN"
+#   echo "$wlan WLAN" > /dev/vfd
+#   sleep 3
+fi
+
+# Start automount
+if [ -e /etc/init.d/automount ]; then
+   python /etc/init.d/automount &
+fi
+
+# inadyn
+inadyn=`cat /etc/enigma2/settings | grep systemoptions.inadyn | cut -d "=" -f2`
+if [ ! $inadyn ] ||  [ ! -e /usr/bin/inadyn ]; then
+   echo "[rcS] No inadyn"
+else
+   if [ -e /usr/bin/inadyn ]; then
+      /usr/bin/inadyn &
+   fi
+fi
+
+# OpenSSh daemon
+openssh=`cat /etc/enigma2/settings | grep systemoptions.openssh | cut -d "=" -f2`
+if [ ! $openssh ] || [ ! -e /etc/init.d/sshd ]; then
+   echo "[rcS] No OpenSSH"
+else
+   if [ -e /etc/init.d/sshd ]; then
+      (sleep 30; /etc/init.d/sshd start) &
+   fi
+fi
+
+# Enable PKT plugins
+if [ ! -e /tmp/reference.dat ] && [ -e /var/bin/reference.dat ]; then
+   cp /var/bin/reference.dat /tmp
+fi
+
+#timefix e2
+date -s "201605011200"
+# Try and synchronise time
+#inettime=`cat /etc/enigma2/settings | grep systemoptions.inettime | cut -d "=" -f2`
+# if [ ! $inettime ] && [ -e /sbin/ntpdate ]; then
+if [ -e /sbin/ntpdate ]; then
+   echo "[rcS] Set internet time"
+   (/sbin/ntpdate nl.pool.ntp.org; /bin/fp_control -sst) &
+else
+   if [ -e /usr/sbin/time.sh ]; then
+      echo "[rcS] Use transponder time"
+      /usr/sbin/time.sh &
+   fi
+fi
+
+echo "[rcS] Init portmap & ftp (LOAD 1)"
+echo "LOAD 1" > /dev/vfd
+/etc/init.d/portmap start
+/etc/init.d/vsftpd start
+/usr/sbin/inetd
+
+# Do own extras
+if [ -e /etc/ownscript.sh ]; then
+   /etc/ownscript.sh &
+fi
+
+#stfbcontrol a 255
+
+echo "Loading E2" > /dev/vfd
+echo "[rcS] Loading E2"
+
+until false
+do
+   echo "[rcS] Entering e2 main loop"
+   if [ -e /usr/local/share/enigma2/backdrop.mvi ]; then
+      showiframe -p /usr/local/share/enigma2/backdrop.mvi &
+   fi
+   /usr/local/bin/enigma2
+   rtv=$?
+   echo "[rcS] e2 ended <- return value: " $rtv
+   /bin/fp_control -i 40 0
+   case "$rtv" in
+      0) echo "E2 ERROR"
+         echo "E2 Error" > /dev/vfd
+         init 6;;
+      1) echo "SHUTDOWN"
+         echo "Shutdown" > /dev/vfd
+         if [ -e /usr/local/share/enigma2/shutdown.mvi ]; then
+            showiframe -p /usr/local/share/enigma2/shutdown.mvi &
+         fi
+         init 0;;
+      2) echo "REBOOT"
+         echo "Reboot" > /dev/vfd
+         init 6;;
+      3) echo "E2 RESTART"
+         echo "Restart GUI" > /dev/vfd
+         echo "0" > /proc/progress
+         if [ -e /usr/local/share/enigma2/backdrop.mvi ]; then
+            showiframe -p /usr/local/share/enigma2/backdrop.mvi &
+         else
+            showiframe -p /boot/bootlogo.mvi &
+         fi;;
+      *) echo "ERROR"
+         echo "Error" > /dev/vfd
+         init 6;;
+   esac
+done
+
 #never reached
-echo "REBOOT HDBOX" > /dev/vfd
-echo "REBOOT HDBOX"
+echo "Reboot FS9000/9200" > /dev/vfd
+echo "Reboot FS9000/9200"
 reboot
+
diff --git a/root/release/rcS_enigma2_hs7110 b/root/release/rcS_enigma2_hs7110
--- a/root/release/rcS_enigma2_hs7110
+++ b/root/release/rcS_enigma2_hs7110
@@ -1,38 +1,38 @@
 #!/bin/sh
-#Version 140727.1
+#Version 170422.1
 
-echo "Fortis HS7110"
+echo "Fortis HS7110 Enigma2"
 
 MODDIR=/lib/modules
 
-echo "Init frontpanel"
-insmod $MODDIR/nuvoton.ko paramDebug=0
+insmod $MODDIR/e2_proc.ko
+
+echo "[rcS] Init frontpanel"
+if [ ! -e /dev/vfd ]; then
+   mknod -m 0660 /dev/vfd c 147 0
+fi
+insmod $MODDIR/nuvoton.ko
 insmod $MODDIR/simu_button.ko
 
 if [ -e /var/etc/.firstboot ]; then
-   echo "WAIT 1 min"
+   echo "[rcS] WAIT 1 minute"
    rm /var/etc/.firstboot
    sleep 1
    touch /dev/.devfsd
 else
-   echo "LOAD 10"
+   echo "[rcS] LOAD 10"
 fi
 
 /etc/init.d/mountvirtfs start
-/etc/init.d/portmap start
 
-insmod $MODDIR/e2_proc.ko
-
-# Start automounter with umount timeout of 5 seconds
-insmod $MODDIR/autofs4.ko
-
+echo "[rcS] Starting automounter"
 /etc/init.d/autofs start
 
-echo "Starting DEBUG Interface"
+echo "[rcS] Starting DEBUG Interface"
 /etc/init.d/mountall start
 /etc/init.d/hostname start
 
-echo -n "Starting telnetd "
+echo -n "[rcS] Starting telnetd "
 autologin=`cat /etc/enigma2/settings | grep systemoptions.autologin | cut -d "=" -f2`
 if [ ! $autologin ]; then
    /usr/sbin/telnetd -l /bin/autologin
@@ -42,24 +42,22 @@ else
    echo "with normal login"
 fi
 
-echo "Init stmfb (LOAD 9"
+echo "[rcS] Init stmfb (LOAD 9)"
 insmod $MODDIR/stmcore-display-sti7111.ko
 
 if grep -q "config.av.videoport=Scart" /etc/enigma2/settings; then
-  insmod $MODDIR/stmfb.ko display0=720x576i-32@50:15m:pal:rgb:rgb; #SCART
+   insmod $MODDIR/stmfb.ko display0=720x576i-32@50:12m:pal:rgb:rgb #SCART
 else
-  insmod $MODDIR/stmfb.ko display0=1280x720-32@50:15m:pal:rgb:rgb; #HDMI
+   insmod $MODDIR/stmfb.ko display0=1280x720-32@50:12m:pal:rgb:rgb #HDMI
 fi
 
-echo "Loading modules"
+echo "[rcS] Loading modules"
 
-if [ ! -e /boot/audio.elf ]; then
-   echo "NO AUDIO FW!!!"
-   echo "NOFW" > /dev/vfd
+if [ ! -e /boot/audio.elf ] || [ ! -e /boot/video.elf ]; then
+   echo "[rcS] Firmware(s) missing!"
 fi
 
-echo "Load audio firmware (LOAD 8)"
-echo "LOAD 8" > /dev/vfd
+echo "[rcS] Load audio firmware (LOAD 8)"
 dtsdown=`cat /etc/enigma2/settings | grep systemoptions.dtsdownmix | cut -d "=" -f2`
 if [ ! $dtsdown ] && [ -e /boot/audio_dts.elf ]; then
    /bin/ustslave /dev/st231-1 /boot/audio_dts.elf > /dev/null
@@ -67,167 +65,225 @@ else
    /bin/ustslave /dev/st231-1 /boot/audio.elf > /dev/null
 fi
 
-echo "Load video firmware (LOAD 7)"
-echo "LD 7" > /dev/vfd
+echo "[rcS] Load video firmware (LOAD 7)"
 /bin/ustslave /dev/st231-0 /boot/video.elf > /dev/null
 
-echo "Init embx (LOAD 6)"
+echo "[rcS] Init embx (LOAD 6)"
 insmod $MODDIR/embxshell.ko
-insmod $MODDIR/embxmailbox.ko mailbox0=0xfe211000:136:set2 mailbox1=0xfe212000:0 ;
-insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0x40000000:0x10000000 ;
+insmod $MODDIR/embxmailbox.ko mailbox0=0xfe211000:136:set2 mailbox1=0xfe212000:0
+insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0x40000000:0x10000000
 insmod $MODDIR/mme_host.ko transport0=shm
 
-echo "Init AVS (LOAD 5)"
+echo "[rcS] Init AVS (LOAD 5)"
 insmod $MODDIR/avs.ko type=avs_none
 
 player=`cat /proc/stb/player/version | awk '{ print substr( $0, length($0) - 2, length($0) ) }'`
-echo "Init player $player (LOAD 4)"
-
+echo "[rcS] Init player $player (LOAD 4)"
 insmod $MODDIR/mmelog.ko
 insmod $MODDIR/ksound.ko
 insmod $MODDIR/p2div64.ko
 insmod $MODDIR/stm_v4l2.ko
-if [ $player -gt 131 ]; then
-   insmod $MODDIR/stmvout.ko
-   insmod $MODDIR/stmvbi.ko
-fi
+insmod $MODDIR/stmvout.ko
+insmod $MODDIR/stmvbi.ko
+
 insmod $MODDIR/pseudocard.ko
 
+echo "[rcS] Init frontend"
 insmod $MODDIR/lnb.ko type=a8293
 insmod $MODDIR/stv090x.ko paramDebug=0
-insmod $MODDIR/hs7110.ko
-if [ $player -gt 131 ]; then
-   insmod $MODDIR/pti.ko
-   insmod $MODDIR/stm_monitor.ko
-   insmod $MODDIR/stmsysfs.ko
-   insmod $MODDIR/stmdvb.ko
-else
-   insmod $MODDIR/pti.ko
-   insmod $MODDIR/stmdvb.ko
-   insmod $MODDIR/stm_monitor.ko
-fi
+mknod /dev/lnb c 149 0
 
-echo "LOAD 3" > /dev/vfd
+echo "[rcS] Init CI & cardreader"
+insmod $MODDIR/hs711x.ko
+insmod $MODDIR/smartcard.ko
+insmod $MODDIR/pti.ko waitMS=20 videoMem=4096
+if [ $?=='2' ]; then
+   insmod $MODDIR/pti.ko
+   echo "[rcS] Simple pti"
+else
+   echo "[rcS] Full feature pti"
+fi
+insmod $MODDIR/stm_monitor.ko
+insmod $MODDIR/stmsysfs.ko
+insmod $MODDIR/stmdvb.ko
+
+echo "[rcS] Init player2 (LOAD 3)"
 insmod $MODDIR/player2.ko
 insmod $MODDIR/sth264pp.ko
 insmod $MODDIR/stmalloc.ko
 insmod $MODDIR/platform.ko
 insmod $MODDIR/silencegen.ko
 
-insmod $MODDIR/smartcard.ko
-
-#echo "Init HDMI-CEC"
-#insmod $MODDIR/cec.ko activemode=1
-
 insmod $MODDIR/bpamem.ko
 mknod /dev/bpamem c 153 0
 
-showiframe -p /boot/bootlogo.mvi &
+echo "[rcS] Init HDMI-CEC"
+if [ -e $MODDIR/cec.ko ];then
+   insmod $MODDIR/cec.ko activemode=1
+fi
+
+if [ -e /boot/bootlogo.mvi ]; then
+   showiframe -p /boot/bootlogo.mvi &
+fi
+
 stfbcontrol a 0
 
-echo "Init lircd (LOAD 2)"
-mknod /dev/rc c 147 1 
-mknod /dev/lnb c 149 0
+if [ -e $MODDIR/exportfs.ko ]; then
+   echo "[rcS] Init exportfs"
+   insmod $MODDIR/exportfs.ko
+fi
 
-echo "Init smartcard cardreader"
-mknod /dev/sci0 c 169 0
+if [ -e $MODDIR/cifs.ko ]; then
+echo "[rcS] Init CIFS support"
+   insmod $MODDIR/cifs.ko
+fi
 
+if [ -e $MODDIR/ntfs.ko ]; then
+   echo "[rcS] Init NTFS support"
+   insmod $MODDIR/ntfs.ko
+fi
+
+if [ -e $MODDIR/tun.ko ]; then
+echo "[rcS] Init tun support"
+   insmod $MODDIR/tun.ko
+fi
+
+if [ -e $MODDIR/usbserial.ko ]; then
+   insmod $MODDIR/usbserial.ko
+   if [ -e $MODDIR/ftdi.ko ]; then
+   echo "[rcS] Init FTDI USB serial support"
+      insmod $MODDIR/ftdi.ko
+   fi
+   if [ -e $MODDIR/pl2303.ko ]; then
+   echo "[rcS] Init PL2303 USB serial support"
+      insmod $MODDIR/pl2303.ko
+   fi
+fi
+
+echo "[rcS] Init remote control (LOAD 2)"
 /bin/evremote2 10 140 &
 
 stfbcontrol a 255
 
-# Why is this done twice?
-#/etc/init.d/mountall start
-#/etc/init.d/hostname start
-
-#echo "Starting telnetd"
-#/usr/sbin/telnetd -l /bin/autologin
-
-wlan=`cat /etc/enigma2/settings | grep systemoptions.wlan | cut -d "=" -f2`
-if [ ! $wlan ] || [ ! -e $MODDIR/$wlan.ko ]; then
-   echo "No WLAN"
-else
-   insmod $MODDIR/$wlan.ko
-   echo "$wlan WLAN"
-fi
-
-if [ -e $MODDIR/ntfs.ko ]; then
-   insmod $MODDIR/ntfs.ko
-fi
-
-if [ -e $MODDIR/cifs.ko ]; then
-   insmod $MODDIR/cifs.ko
-fi
-
-echo "LD 1" > /dev/vfd
-/etc/init.d/vsftpd start
-/usr/sbin/inetd
-
 NFS=`grep -c nfs /proc/cmdline`
 if [ "$NFS" -eq "1" ]; then
-   echo "Booting from nfs, don't set network"
+   echo "[rcS] Booting from NFS, don't set network"
 else
    if [ -e /etc/network/interfaces ]; then
       ip addr flush eth0
       /etc/init.d/networking stop
-      DHCP=`grep -c dhcp /etc/network/interfaces`
+      DHCP=`grep -c 'iface eth0 inet dhcp' /etc/network/interfaces`
       if [ "$DHCP" -eq "1" ]; then
-         echo "Starting DHCP"
+         echo "[rcS] Starting DHCP"
          /etc/init.d/udhcpc start
       fi
       /etc/init.d/networking start
    fi
 fi
+#Allow network to wake up and initialize
+sleep 2
+#Show IP address on frontpanel
+#ip=`ifconfig eth0 | sed -n '/inet addr/s/.*addr.\([^ ]*\) .*/\1/p'`
+#echo "IP $ip" > /dev/vfd
+#sleep 3
+
+echo -n "[rcS] Init WLAN: "
+wlan=`cat /etc/enigma2/settings | grep systemoptions.wlan | cut -d "=" -f2`
+if [ ! $wlan ] || [ ! -e $MODDIR/$wlan.ko ]; then
+   echo "None."
+else
+   insmod $MODDIR/$wlan.ko
+   echo "$wlan"
+#   echo "$wlan WLAN" > /dev/vfd
+#   sleep 3
+fi
+
+# Handle SWAPPART and RECORD labels and USB devices
+if [ -e /usr/sbin/amount.sh ]; then
+   (sleep 20; /usr/sbin/amount.sh) &
+fi
+
+# inadyn
+inadyn=`cat /etc/enigma2/settings | grep systemoptions.inadyn | cut -d "=" -f2`
+if [ ! $inadyn ] ||  [ ! -e /usr/bin/inadyn ]; then
+   echo "[rcS] No inadyn"
+else
+   if [ -e /usr/bin/inadyn ]; then
+      /usr/bin/inadyn &
+   fi
+fi
+
+# OpenSSh daemon
+openssh=`cat /etc/enigma2/settings | grep systemoptions.openssh | cut -d "=" -f2`
+if [ ! $openssh ] || [ ! -e /etc/init.d/sshd ]; then
+   echo "[rcS] No OpenSSH"
+else
+   if [ -e /etc/init.d/sshd ]; then
+      (sleep 30; /etc/init.d/sshd start) &
+   fi
+fi
+
+# Enable PKT plugins
+if [ ! -e /tmp/reference.dat ] && [ -e /var/bin/reference.dat ]; then
+   cp /var/bin/reference.dat /tmp
+fi
+
+# Try and synchronise time
+#inettime=`cat /etc/enigma2/settings | grep systemoptions.inettime | cut -d "=" -f2`
+# if [ ! $inettime ] && [ -e /sbin/ntpdate ]; then
+if [ -e /sbin/ntpdate ]; then
+   echo "[rcS] Set internet time"
+   (/sbin/ntpdate nl.pool.ntp.org; /bin/fp_control -sst) &
+else
+   if [ -e /usr/sbin/time.sh ]; then
+      echo "[rcS] Use transponder time"
+      /usr/sbin/time.sh &
+   fi
+fi
+
+echo "[rcS] Init portmap & ftp (LOAD 1)"
+/etc/init.d/portmap start
+/etc/init.d/vsftpd start
+/usr/sbin/inetd
 
 # Do own extras
 if [ -e /etc/ownscript.sh ]; then
    /etc/ownscript.sh &
 fi
 
-# Try and synchronise time
-inettime=`cat /etc/enigma2/settings | grep systemoptions.inettime | cut -d "=" -f2`
-if [ ! $inettime ] && [ -e /sbin/ntpdate ]; then
-   echo "Set internet time"
-#   (/sbin/ntpdate pl.pool.ntp.org; /bin/fp_control -s `date +"%H:%M:%S %d-%m-%Y"`) &
-   (/sbin/ntpdate ntp.nasa.gov; /bin/fp_control -s `date +"%H:%M:%S %d-%m-%Y"`) &
-else
-   if [ -e /usr/sbin/time.sh ]; then
-      echo "Use transponder time"
-      /usr/sbin/time.sh &
-   fi
-fi
-
-echo "Start Enigma2"
-echo "LDE2" > /dev/vfd
+echo "[rcS] Loading E2"
 
 until false
 do
-   echo "Entering e2 main loop"
+   echo "[rcS] Entering e2 main loop"
    if [ -e /usr/local/share/enigma2/backdrop.mvi ]; then
-      showiframe -p /usr/local/share/enigma2/backdrop.mvi
+      showiframe -p /usr/local/share/enigma2/backdrop.mvi &
    fi
    /usr/local/bin/enigma2
    rtv=$?
-   echo "e2 ended <- RTV: " $rtv
+   echo "[rcS] e2 ended <- return value: " $rtv
    case "$rtv" in
-      0) echo "0"
-         echo "E2 ERROR"
+      0) echo "E2 ERROR"
          init 6;;
-      1) echo "1"
-         echo "SHUTDOWN"
+      1) echo "SHUTDOWN"
+         if [ -e /usr/local/share/enigma2/shutdown.mvi ]; then
+            showiframe -p /usr/local/share/enigma2/shutdown.mvi &
+         fi
          init 0;;
-      2) echo "2"
-         echo "REBOOT"
+      2) echo "REBOOT"
          init 6;;
-      3) echo "3"
-         echo "E2 RESTART"
+      3) echo "E2 RESTART"
          echo "0" > /proc/progress
-         showiframe -p /boot/bootlogo.mvi &;;
-      *) echo "*"
-         echo "ERROR"
+         if [ -e /usr/local/share/enigma2/backdrop.mvi ]; then
+            showiframe -p /usr/local/share/enigma2/backdrop.mvi &
+         else
+            showiframe -p /boot/bootlogo.mvi &
+         fi
+         echo -n " ";;
+      *) echo "ERROR"
          init 6;;
    esac
-done 
+done
 
 #never reached
 echo "REBOOT HS7110"
diff --git a/root/release/rcS_enigma2_spark b/root/release/rcS_enigma2_spark
--- a/root/release/rcS_enigma2_spark
+++ b/root/release/rcS_enigma2_spark
@@ -1,172 +1,327 @@
 #!/bin/sh
+#Version 151120.1
 
 MODDIR=/lib/modules
-echo "init frontpanel"
-insmod $MODDIR/aotom.ko
+
+echo "Spark Enigma2"
+
+insmod $MODDIR/e2_proc.ko
+
+insmod $MODDIR/aotom.ko paramDebug=0
 insmod $MODDIR/simu_button.ko
+if [ -e $MODDIR/encrypt.ko ]; then
+   insmod $MODDIR/encrypt.ko
+fi
 
 if [ -e /var/etc/.firstboot ]; then
-   echo "WAIT 1 min" >/dev/vfd
-   echo "WAIT 1 min"
+   echo "1MIN" >/dev/vfd
+   echo "WAIT 1 minute"
    rm /var/etc/.firstboot
+   sleep 1
    touch /dev/.devfsd
+else
+   echo "LD10" >/dev/vfd
+   echo "LOAD 10"
 fi
 
 /etc/init.d/mountvirtfs start
 /etc/init.d/portmap start
-
-insmod $MODDIR/e2_proc.ko
-
 /etc/init.d/autofs start
 
-if [ ! -e /var/etc/.firstboot ]; then
-
-   echo "Starting DEBUG Interface"
-   /etc/init.d/mountall start
-   /etc/init.d/hostname start
-
-   echo "starting telnetd"
-   /usr/sbin/telnetd -l /bin/autologin 
-
-   echo "init stmfb"
-   insmod $MODDIR/stmcore-display-sti7111.ko
-   insmod $MODDIR/stmfb.ko display0=1280x720-32@50:15m:pal:yuv:yuv
-
-   echo "LOADING MODULES"   
-   echo "LOAD" > /dev/vfd
-
-   if [ ! -e /boot/audio.elf ]; then
-      echo "FW MISSING!!!"
-   fi
-
-   echo "load a firmware"
-   /bin/ustslave /dev/st231-1 /boot/audio.elf
-   echo "load v firmware"
-   /bin/ustslave /dev/st231-0 /boot/video.elf
-
-   echo "init embx"
-   insmod $MODDIR/embxshell.ko
-   insmod $MODDIR/embxmailbox.ko mailbox0=0xfe211000:136:set2 mailbox1=0xfe212000:0 ;
-   insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0x40000000:0x10000000 ;
-   insmod $MODDIR/mme_host.ko transport0=shm
-
-   echo "init AVS"
-   insmod $MODDIR/avs.ko type=avs_pio
-
-   player=`cat /proc/stb/player/version | awk '{ print substr( $0, length($0) - 2, length($0) ) }'`
-   echo "init player $player"
-
-   insmod $MODDIR/mmelog.ko
-   insmod $MODDIR/ksound.ko
-   insmod $MODDIR/p2div64.ko
-   insmod $MODDIR/stm_v4l2.ko
-   if [ $player -gt 131 ]; then
-      insmod $MODDIR/stmvout.ko
-      insmod $MODDIR/stmvbi.ko
-   fi
-   insmod $MODDIR/pseudocard.ko
-
-   insmod $MODDIR/stv090x.ko
-   if [ $player -gt 131 ]; then
-      # Full feature pti
-      insmod $MODDIR/pti.ko waitMS=20 videoMem=4096
-      if [ $?=='2' ]; then
-         # Simple pti
-         insmod $MODDIR/pti.ko
-      fi
-      insmod $MODDIR/stm_monitor.ko
-      insmod $MODDIR/stmsysfs.ko
-      insmod $MODDIR/stmdvb.ko
-   else
-      insmod $MODDIR/pti.ko
-      insmod $MODDIR/stmdvb.ko
-      insmod $MODDIR/stm_monitor.ko
-   fi
-   insmod $MODDIR/player2.ko
-   insmod $MODDIR/sth264pp.ko
-   insmod $MODDIR/stmalloc.ko
-   insmod $MODDIR/platform.ko
-   insmod $MODDIR/silencegen.ko
-   insmod $MODDIR/smartcard.ko
-   insmod $MODDIR/cec.ko activemode=1
-
-   insmod $MODDIR/bpamem.ko
-   mknod /dev/bpamem c 153 0 
-
-   showiframe -p /var/boot/bootlogo.mvi &
-   stfbcontrol a 0
-
-   echo "init lircd"
-   mkdir -p /var/run/lirc
-   /usr/bin/lircd
-
-   mknod /dev/rc c 147 1 
-   mknod /dev/sci0 c 169 0
-   mknod /dev/sci1 c 169 1 
-   major=$(awk "\$2==\"sparkid\" {print \$1}" /proc/devices)
-   rm -f /dev/sparkid
-   mknod /dev/sparkid c $major 0 
-
-   /bin/evremote2 10 100 &
-
-   stfbcontrol a 255
-
-   /etc/init.d/mountall start
-   /etc/init.d/hostname start
-
-   echo "starting telnetd"
-   /usr/sbin/telnetd -l /bin/autologin
-   /etc/init.d/vsftpd start
-   /usr/sbin/inetd
-
-   NFS=`grep -c nfs /proc/cmdline`
-   if [ "$NFS" -eq "1" ]; then 
-      echo "Booting from nfs, don't set network" 
-   else 
-      if [ -e /etc/network/interfaces ]; then 
-	 ip addr flush eth0 
-	 /etc/init.d/networking stop 
-	 DHCP=`grep -c dhcp /etc/network/interfaces`
-	 if [ "$DHCP" -eq "1" ]; then 
-	    echo "Starting dhcp"
-            /etc/init.d/udhcpc start 
-	 fi 
-	 /etc/init.d/networking start 
-      fi 
-   fi
-
-   echo "run" > /dev/vfd
-   echo "LOADING E2"
-
-   until false
-   do
-      echo "starting e2->"
-      /usr/local/bin/enigma2
-      rtv=$?
-      echo "e2 ended <- RTV: " $rtv
-      case "$rtv" in
-		0) echo "0"
-		   echo "E2 ERROR"
-		   init 6;;
-		1) echo "1"
-		   echo "SHUTDOWN"
-		   init 0;;
-		2) echo "2"
-		   echo "REBOOT"
-		   init 6;;
-		3) echo "3"
-		   echo "E2 RESTART"
-		   echo "0" > /proc/progress
-		   showiframe -p /var/boot/bootlogo.mvi &;;
-		*) echo "*"
-		   echo "ERROR"
-		   init 6;;
-      esac
-   done 
+if [ -e "$MODDIR/cpu_frequ.ko" ]; then
+   insmod $MODDIR/cpu_frequ.ko
+   cpufreq=`cat /etc/enigma2/settings | grep systemoptions.freq | cut -d "=" -f2`
+   case $cpufreq in
+      200) overclk=5123;;
+      300) overclk=2561;;
+      450) overclk=3841;;
+      500) overclk=12803;;
+      540) overclk=4609;;
+      600) overclk=5121;;
+      630) overclk=5377;;
+      650) overclk=16643;;
+      700) overclk=17923;;
+      710) overclk=18179;;
+      750) overclk=19203;;
+      775) overclk=39686;;
+      800) overclk=20483;;
+      *)   cpufreq=540
+           overclk=4609;;
+   esac
+   echo $overclk > /proc/cpu_frequ/pll0_ndiv_mdiv
+   echo "Setting CPU clock speed to $cpufreq MHz (overclk=$overclk)"
 fi
 
+echo "Starting DEBUG Interface"
+/etc/init.d/mountall start
+/etc/init.d/hostname start
+
+echo -n "Starting telnetd "
+autologin=`cat /etc/enigma2/settings | grep systemoptions.autologin | cut -d "=" -f2`
+if [ ! $autologin ]; then
+   /usr/sbin/telnetd -l /bin/autologin
+   echo "with autologin"
+else
+   /usr/sbin/telnetd -l /bin/login
+   echo "with normal login"
+fi
+
+echo "Init stmfb (LOAD 9)"
+echo "LD 9" >/dev/vfd
+insmod $MODDIR/stmcore-display-sti7111.ko
+
+if  grep -q "config.av.videoport=Scart" /etc/enigma2/settings; then
+   insmod $MODDIR/stmfb.ko display0=720x576i-32@50:15m:pal:rgb:rgb; #SCART
+else
+   insmod $MODDIR/stmfb.ko display0=1280x720-32@50:15m:pal:yuv:yuv; #HDMI
+fi
+
+echo "Loading modules"
+
+if [ ! -e /boot/audio.elf ] || [ ! -e /boot/video.elf ]; then
+   echo "NO FIRMWARE(S)!!!"
+   echo "NOFW" > /dev/vfd
+fi
+
+echo "Load audio firmware (LOAD 8)"
+echo "LD 8" > /dev/vfd
+dtsdown=`cat /etc/enigma2/settings | grep systemoptions.dtsdownmix | cut -d "=" -f2`
+if [ ! $dtsdown ] && [ -e /boot/audio_dts.elf ]; then
+   /bin/ustslave /dev/st231-1 /boot/audio_dts.elf > /dev/null
+else
+   /bin/ustslave /dev/st231-1 /boot/audio.elf > /dev/null
+fi
+
+echo "Load video firmware (LOAD 7)"
+echo "LD 7" > /dev/vfd
+/bin/ustslave /dev/st231-0 /boot/video.elf > /dev/null
+
+echo "Init embx (LOAD 6)"
+echo "LD 6" > /dev/vfd
+insmod $MODDIR/embxshell.ko
+insmod $MODDIR/embxmailbox.ko mailbox0=0xfe211000:136:set2 mailbox1=0xfe212000:0 ;
+insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0x40000000:0x10000000 ;
+insmod $MODDIR/mme_host.ko transport0=shm
+
+echo "Init AVS (LOAD 5)"
+echo "LD 5" > /dev/vfd
+insmod $MODDIR/avs.ko type=avs_none
+
+player=`cat /proc/stb/player/version | awk '{ print substr( $0, length($0) - 2, length($0) ) }'`
+echo "Init player $player (LOAD 4)"
+echo "LD 4" > /dev/vfd
+
+insmod $MODDIR/mmelog.ko
+insmod $MODDIR/ksound.ko
+insmod $MODDIR/p2div64.ko
+insmod $MODDIR/stm_v4l2.ko
+insmod $MODDIR/stmvout.ko
+insmod $MODDIR/stmvbi.ko
+
+insmod $MODDIR/pseudocard.ko
+
+insmod $MODDIR/stv090x.ko
+
+if [ -e $MODDIR/pti.ko ]; then
+   insmod $MODDIR/pti.ko waitMS=20 videoMem=4096
+   if [ ! $?=='2' ]; then
+      pti_arg=""
+      echo "Simple pti"
+      insmod $MODDIR/pti.ko $pti_arg
+   fi
+fi
+insmod $MODDIR/stm_monitor.ko
+insmod $MODDIR/stmsysfs.ko
+insmod $MODDIR/stmdvb.ko
+
+echo "LD 3" > /dev/vfd
+echo "LOAD 3"
+#insmod $MODDIR/player2.ko discardlateframe=0
+insmod $MODDIR/player2.ko
+insmod $MODDIR/sth264pp.ko
+insmod $MODDIR/stmalloc.ko
+insmod $MODDIR/platform.ko
+insmod $MODDIR/silencegen.ko
+
+insmod $MODDIR/smartcard.ko
+
+echo "Init HDMI-CEC"
+insmod $MODDIR/cec.ko activemode=1
+
+insmod $MODDIR/bpamem.ko
+mknod /dev/bpamem c 153 0 
+
+showiframe -p /boot/bootlogo.mvi &
+stfbcontrol a 0
+
+echo "Init lircd (LOAD 2)"
+echo "LD 2" > /dev/vfd
+/usr/bin/lircd
+rm -rf /dev/rc
+mknod /dev/rc c 147 1
+
+echo "Init smartcard cardreader"
+mknod /dev/sci0 c 169 0
+mknod /dev/sci1 c 169 1
+
+/bin/evremote2 10 100 &
+
+stfbcontrol a 255
+
+wlan=`cat /etc/enigma2/settings | grep systemoptions.wlan | cut -d "=" -f2`
+if [ ! $wlan ] || [ ! -e $MODDIR/$wlan.ko ]; then
+   echo "No WLAN"
+else
+   insmod $MODDIR/$wlan.ko
+   echo "$wlan WLAN"
+#   echo "$wlan WLAN" > /dev/vfd
+#   sleep 3
+fi
+
+if [ -e $MODDIR/ntfs.ko ]; then
+   insmod $MODDIR/ntfs.ko
+fi
+
+if [ -e $MODDIR/cifs.ko ]; then
+   insmod $MODDIR/cifs.ko
+fi
+
+echo "LD 1" > /dev/vfd
+echo "Init FTP (LOAD 1)"
+/etc/init.d/vsftpd start
+/usr/sbin/inetd
+
+NFS=`grep -c nfs /proc/cmdline`
+if [ "$NFS" -eq "1" ]; then 
+   echo "Booting from nfs, don't set network" 
+else 
+   if [ -e /etc/network/interfaces ]; then 
+      ip addr flush eth0
+      /etc/init.d/networking stop 
+      DHCP=`grep -c 'iface eth0 inet dhcp' /etc/network/interfaces`
+      if [ "$DHCP" -eq "1" ]; then
+         echo "Starting DHCP on eth0"
+         /etc/init.d/udhcpc start
+      fi
+      /etc/init.d/networking start &
+   fi
+fi
+sleep 2
+
+# Handle SWAPPART and RECORD labels and USB devices
+if [ -e /usr/sbin/amount.sh ]; then
+   (sleep 20; /usr/sbin/amount.sh) &
+fi
+
+# inadyn
+inadyn=`cat /etc/enigma2/settings | grep systemoptions.inadyn | cut -d "=" -f2`
+if [ ! $inadyn ]; then
+   echo "No inadyn"
+else
+   if [ -e /usr/bin/inadyn ]; then
+      /usr/bin/inadyn &
+#   else
+#      echo "INADYN MISSING" > /dev/vfd
+#      sleep 2
+   fi
+fi
+
+# OpenSSh daemon
+openssh=`cat /etc/enigma2/settings | grep systemoptions.openssh | cut -d "=" -f2`
+if [ ! $openssh ]; then
+   echo "No OpenSSH"
+else
+   if [ -e /etc/init.d/sshd ]; then
+      (sleep 30; /etc/init.d/sshd start) &
+#   else
+#      echo "SSHD MISSING" > /dev/vfd
+#      sleep 2
+   fi
+fi
+
+# Enable PKT plugins
+if [ ! -e /tmp/reference.dat ] && [ -e /var/bin/reference.dat ]; then
+  cp /var/bin/reference.dat /tmp
+fi
+
+# Start automount
+if [ -e /etc/init.d/automount ]; then
+   python /etc/init.d/automount &
+fi
+
+# Do own extras
+if [ -e /etc/ownscript.sh ]; then
+   /etc/ownscript.sh &
+fi
+
+# Try and synchronise time
+inettime=`cat /etc/enigma2/settings | grep systemoptions.inettime | cut -d "=" -f2`
+if [ ! $inettime ] && [ -e /sbin/ntpdate ]; then
+   echo "Set internet time"
+   /sbin/ntpdate de.pool.ntp.org
+else
+   if [ -e /usr/sbin/time.sh ]; then
+      echo "Use transponder time"
+      /usr/sbin/time.sh &
+   fi
+fi
+
+echo "Start Enigma2"
+echo "Start Enigma2" > /dev/vfd
+
+until false
+do
+   echo "Entering E2 main loop"
+#   if [ -e /usr/local/share/enigma2/backdrop.mvi ]; then
+#      showiframe -p /usr/local/share/enigma2/backdrop.mvi
+#   fi
+   /usr/local/bin/enigma2
+   rtv=$?
+   echo "E2 ended <- RTV:" $rtv
+   case "$rtv" in
+      0)  echo "E2Er" > /dev/vfd
+          init 6;;
+      1)  echo "Shdn" > /dev/vfd
+          if [ -e /usr/local/share/enigma2/shutdown.mvi ]; then
+             showiframe -p /usr/local/share/enigma2/shutdown.mvi
+          fi
+          init 0;;
+      2)  echo "rEbt" > /dev/vfd
+          init 6;;
+      3)  echo "RESTART GUI" > /dev/vfd
+          echo "0" > /proc/progress
+#          if [ -e /usr/local/share/enigma2/backdrop.mvi ]; then
+#             showiframe -p /usr/local/share/enigma2/backdrop.mvi
+#          else
+             showiframe -p /boot/bootlogo.mvi &;;
+#          fi
+      10) echo "SPARK RESTART"
+          echo "SPrK" > /dev/vfd
+          insmod $MODDIR/i2s.ko
+          if [ ! -f /etc/fw_env.config ]; then
+             echo "fw_env.config not found - will create it"
+             echo '/dev/mtd7 0x000A0000 0x00020000 0x20000' > /etc/fw_env.config
+          fi
+          var=`fw_printenv | grep 'bootargs_spark='` ; fw_setenv bootargs ${var#*=}
+          var=`fw_printenv | grep 'bootcmd_spark='` ; fw_setenv bootcmd ${var#*=}
+          var=`fw_printenv | grep 'boot_system_spark='` ; fw_setenv boot_system ${var#*=}
+          var=`fw_printenv | grep 'userfs_base_spark='` ; fw_setenv userfs_base ${var#*=}
+          var=`fw_printenv | grep 'userfs_len_spark='` ; fw_setenv userfs_len ${var#*=}
+          var=`fw_printenv | grep 'kernel_base_spark='` ; fw_setenv kernel_base ${var#*=}
+          var=`fw_printenv | grep 'kernel_name_spark='` ; fw_setenv kernel_name ${var#*=}
+          var=`fw_printenv | grep 'userfs_name_spark='` ; fw_setenv userfs_name ${var#*=} 
+          var=`fw_printenv | grep 'loadu_userfs_spark='` ; fw_setenv loadu_userfs ${var#*=}
+          var=`fw_printenv | grep 'loadu_kernel_spark='` ; fw_setenv loadu_kernel ${var#*=}
+          var=`fw_printenv | grep 'kernel_len_spark='` ; fw_setenv kernel_len ${var#*=}
+          sync
+          init 6;;
+      *)  echo "ERROR"
+          echo "Err" > /dev/vfd
+          init 6;;
+   esac
+done 
+
 #never reached
-echo "REBOOT SPARK" > /dev/vfd
+echo "rEbt" > /dev/vfd
 echo "REBOOT SPARK"
 reboot -f
-
diff --git a/root/release/rcS_neutrino_spark7162 b/root/release/rcS_neutrino_spark7162
--- a/root/release/rcS_neutrino_spark7162
+++ b/root/release/rcS_neutrino_spark7162
@@ -1,161 +1,246 @@
 #!/bin/sh
+#Version 151125.1
+
+echo "Spark 7162 Neutrino"
 
 MODDIR=/lib/modules
-echo "init frontpanel"
-insmod $MODDIR/aotom.ko
-#insmod $MODDIR/simu_button.ko
+
+insmod $MODDIR/e2_proc.ko
+
+echo "Init frontpanel"
+insmod $MODDIR/aotom.ko paramDebug=0
 
 if [ -e /var/etc/.firstboot ]; then
-   echo "WAIT 1 min" >/dev/vfd
+   echo "Wait 1 min." > /dev/vfd
    echo "WAIT 1 min"
    rm /var/etc/.firstboot
+   sleep 1
    touch /dev/.devfsd
+else
+   echo "Load 10" > /dev/vfd
+   echo "LOAD 10"
 fi
 
 /etc/init.d/mountvirtfs start
 /etc/init.d/portmap start
 
-insmod $MODDIR/e2_proc.ko
+#if [ -e "$MODDIR/cpu_frequ.ko" ]; then
+#   insmod $MODDIR/cpu_frequ.ko
+#   cpufreq=`cat /etc/enigma2/settings | grep systemoptions.freq | cut -d "=" -f2`
+#   case $cpufreq in
+#      200) overclk=5123;;
+#      300) overclk=2561;;
+#      450) overclk=3841;;
+#      500) overclk=12803;;
+#      540) overclk=4609;;
+#      600) overclk=5121;;
+#      630) overclk=5377;;
+#      650) overclk=16643;;
+#      700) overclk=17923;;
+#      710) overclk=18179;;
+#      750) overclk=19203;;
+#      775) overclk=39686;;
+#      800) overclk=20483;;
+#      *)   cpufreq=540
+#           overclk=4609;;
+#   esac
+#   echo $overclk > /proc/cpu_frequ/pll0_ndiv_mdiv
+#   echo "Setting CPU clock speed to $cpufreq MHz (overclk=$overclk)"
+#fi
 
+echo "Starting DEBUG Interface"
+/etc/init.d/mountall start
+/etc/init.d/hostname start
 
-if [ ! -e /var/etc/.firstboot ]; then
+echo "Init stmfb (LOAD 9)"
+echo "Load 9" > /dev/vfd
+insmod $MODDIR/stmcore-display-sti7105.ko
+insmod $MODDIR/stmfb.ko display0=1280x720-32@50:12m:pal:rgb:rgb; #HDMI
 
-   echo "Starting DEBUG Interface"
-   /etc/init.d/mountall start
-   /etc/init.d/hostname start
+echo "Loading modules"
 
-#   echo "starting telnetd"
-#   /usr/sbin/telnetd -l /bin/autologin
+if [ ! -e /lib/firmware/audio.elf ] || [ ! -e /lib/firmware/video.elf ]; then
+   echo "FIRMWARE MISSING!"
+   echo "FW MISSING!" > /dev/vfd
+fi
 
-   echo "init stmfb"
-   insmod $MODDIR/stmcore-display-sti7105.ko
-   insmod $MODDIR/stmfb.ko display0=1280x720-32@50:12m:pal:yuv:yuv
+echo "Load audio firmware (LOAD 8)"
+echo "Load 8" > /dev/vfd
+if [ -e /lib/firmware/audio_dts.elf ]; then
+   /bin/ustslave /dev/st231-1 /lib/firmware/audio_dts.elf > /dev/null
+else
+   /bin/ustslave /dev/st231-1 /lib/firmware/audio.elf > /dev/null
+fi
 
-   echo "LOADING MODULES"
-   echo "LOAD" > /dev/vfd
+echo "Load video firmware (LOAD 7)"
+echo "Load 7" > /dev/vfd
+/bin/ustslave /dev/st231-0 /lib/firmware/video.elf > /dev/null
 
-   if [ ! -e /lib/firmware/audio.elf ]; then
-      echo "FW MISSING!!!"
-   fi
+echo "Init embx (LOAD 6)"
+echo "Load 6" > /dev/vfd
+insmod $MODDIR/embxshell.ko
+insmod $MODDIR/embxmailbox.ko mailbox0=0xfe211000:136:set2 mailbox1=0xfe212000:0
+insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0x40000000:0x10000000
+insmod $MODDIR/mme_host.ko transport0=shm
 
-   echo "load video firmware"
-   /bin/dd if=/dev/zero of=/dev/st231-0 bs=1024 count=4096
-#   /bin/stslave -t st231.0 -R /lib/firmware/video.elf
-   /bin/ustslave /dev/st231-0 /lib/firmware/video.elf
+echo "Init AVS (LOAD 5)"
+echo "Load 5" > /dev/vfd
+insmod $MODDIR/avs.ko type=avs_pio
 
-   echo "load audio firmware"
-   /bin/dd if=/dev/zero of=/dev/st231-1 bs=1024 count=4096
-#   /bin/stslave -t st231.1 -R /lib/firmware/audio.elf
-   /bin/ustslave /dev/st231-1 /lib/firmware/audio.elf
+player=`cat /proc/stb/player/version | awk '{ print substr( $0, length($0) - 2, length($0) ) }'`
+echo "Init player $player (LOAD 4)"
+echo "Load 4" > /dev/vfd
 
-   echo "init embx"
-   insmod $MODDIR/embxshell.ko
-   insmod $MODDIR/embxmailbox.ko mailbox0=0xfe211000:136:set2 mailbox1=0xfe212000:0
-   insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0x40000000:0x10000000
-   insmod $MODDIR/mme_host.ko transport0=shm
+insmod $MODDIR/mmelog.ko
+insmod $MODDIR/ksound.ko
+insmod $MODDIR/p2div64.ko
+insmod $MODDIR/stm_v4l2.ko
+insmod $MODDIR/stmvout.ko
+insmod $MODDIR/stmvbi.ko
+insmod $MODDIR/pseudocard.ko
 
-   echo "init AVS"
-   insmod $MODDIR/avs.ko type=avs_none
+#Set desired mode for tuner 3 here: t=DVB-T, c=DVB-C
+tunertype='t'
+insmod $MODDIR/spark7162.ko UnionTunerType=$tunertype
 
-   player=`cat /proc/stb/player/version`
-   player=`cat /proc/stb/player/version | awk '{ print substr( $0, length($0) - 2, length($0) ) }'`
-   echo "init player $player"
-   insmod $MODDIR/mmelog.ko
-   insmod $MODDIR/ksound.ko
-   insmod $MODDIR/p2div64.ko
-   insmod $MODDIR/stm_v4l2.ko
-   insmod $MODDIR/stmvout.ko
-   insmod $MODDIR/stmvbi.ko
-   insmod $MODDIR/pseudocard.ko
+#pti_arg="waitMS=20 videoMem=4096"
+#echo "Full feature pti"
+pti_arg=""
+echo "Simple pti"
+insmod $MODDIR/pti.ko $pti_arg
+insmod $MODDIR/stm_monitor.ko
+insmod $MODDIR/stmsysfs.ko
+insmod $MODDIR/stmdvb.ko
 
-   insmod $MODDIR/spark7162.ko UnionTunerType=t
-   insmod $MODDIR/pti.ko
-   insmod $MODDIR/stm_monitor.ko
-   insmod $MODDIR/stmsysfs.ko
-   insmod $MODDIR/stmdvb.ko
-   insmod $MODDIR/player2.ko
-   insmod $MODDIR/sth264pp.ko
-   insmod $MODDIR/stmalloc.ko
-   insmod $MODDIR/platform.ko
-   insmod $MODDIR/silencegen.ko
-   insmod $MODDIR/smartcard.ko
-   insmod $MODDIR/bpamem.ko
+echo "Load 3" > /dev/vfd
+echo "LOAD 3"
+insmod $MODDIR/player2.ko
+insmod $MODDIR/sth264pp.ko
+insmod $MODDIR/stmalloc.ko
+insmod $MODDIR/platform.ko
+insmod $MODDIR/silencegen.ko
+insmod $MODDIR/smartcard.ko
+insmod $MODDIR/bpamem.ko
 
-   stfbcontrol a 0
+if [ -e /boot/neutrinologo_720.mvi ]; then
+   showiframe -p /boot/neutrinologo_720.mvi &
+fi
 
-   echo "init lircd"
-   mkdir -p /var/run/lirc
-   /usr/bin/lircd -u
+stfbcontrol a 0
 
-#   major=$(awk "\$2==\"sparkid\" {print \$1}" /proc/devices)
-#   rm -f /dev/sparkid
-#   mknod /dev/sparkid c $major 0
+if [ -e $MODDIR/cec.ko ]; then
+   echo "Init HDMI-CEC"
+   insmod $MODDIR/cec.ko activemode=1
+fi
+
+echo "Init lircd (LOAD 2)"
+echo "Load 2" > /dev/vfd
+mkdir -p /var/run/lirc
+/usr/bin/lircd -u
+
+#major=$(awk "\$2==\"sparkid\" {print \$1}" /proc/devices)
+#rm -f /dev/sparkid
+#mknod /dev/sparkid c $major 0
 #   rm /f /dev/dvb/adapter0/ca1
 #   mknod /dev/dvb/adapter0/ca1 c 212 22
 
-# Module aus modules.extra laden
-   [ -f /var/etc/modules.extra ] && eval `sed -e 's/#.*//' -e '/^\s*$/d' -e 's/^\(.*\)/insmod \0;/' < /var/etc/modules.extra`
+#echo "Init smartcard cardreader"
+#mknod /dev/sci0 c 169 0
+#mknod /dev/sci1 c 169 1
 
-   stfbcontrol a 255
+stfbcontrol a 255
 
-   # start automounter with umount timeout of 5 seconds
-   MKDIR -p /tmp/autofs
-   insmod $MODDIR/autofs4.ko
+#wlan=`cat /etc/enigma2/settings | grep systemoptions.wlan | cut -d "=" -f2`
+#if [ ! $wlan ] || [ ! -e $MODDIR/$wlan.ko ]; then
+#   echo "No WLAN"
+#else
+#   insmod $MODDIR/$wlan.ko
+#   echo "$wlan WLAN"
+##   echo "$wlan WLAN" > /dev/vfd
+##   sleep 3
+#fi
+
+# Start automounter with umount timeout of 5 seconds
+mkdir -p /tmp/autofs
+insmod $MODDIR/autofs4.ko
+if [ -e /etc/init.d/automount ]; then
    /usr/sbin/automount --ghost --timeout=5 /tmp/autofs file /etc/auto.usb
-
-#   echo "starting vsftpd"
-#   /etc/init.d/vsftpd start
-   /usr/sbin/inetd
-
-   NFS=`grep -c nfs /proc/cmdline`
-   if [ "$NFS" -eq "1" ]; then
-      echo "Booting from nfs, don't set network"
-   else
-      if [ -e /etc/network/interfaces ]; then
-	 ip addr flush eth0
-	 /etc/init.d/networking stop
-	 DHCP=`grep -c dhcp /etc/network/interfaces`
-	 if [ "$DHCP" -eq "1" ]; then
-	    echo "Starting dhcp"
-            /etc/init.d/udhcpc start
-	 fi
-	 /etc/init.d/networking start
-      fi
-   fi
-
-   #timefix
-   date -s "200901011200"
-
-   # Set Display Time
-   (sleep 25;fp_control -s `date +"%H:%M:%S %d-%m-%Y"`) &
-
-   #tuner workaround
-   export FE_OFFSET=1
-
-   echo "run" > /dev/vfd
-   echo "LOADING neutrino"
-
-   until false
-   do
-      echo "starting neutrino ->"
-      /usr/local/bin/neutrino
-      rtv=$?
-      echo "neutrino ended <- RTV: " $rtv
-      case "$rtv" in
-		0) echo "0"
-		   echo "SHUTDOWN"
-		   init 0;;
-		1) echo "1"
-		   echo "REBOOT"
-		   init 6;;
-		*) echo "*"
-		   echo "ERROR"
-		   init 6;;
-      esac
-   done
 fi
 
+if [ -e $MODDIR/ntfs.ko ]; then
+   insmod $MODDIR/ntfs.ko
+fi
+
+if [ -e $MODDIR/cifs.ko ]; then
+   insmod $MODDIR/cifs.ko
+fi
+
+echo "Init FTP (LOAD 1)"
+echo "Load 1" > /dev/vfd
+/etc/init.d/vsftpd start
+/usr/sbin/inetd
+
+NFS=`grep -c nfs /proc/cmdline`
+if [ "$NFS" -eq "1" ]; then
+   echo "Booting from nfs, don't set network"
+else
+   if [ -e /etc/network/interfaces ]; then
+      ip addr flush eth0
+      /etc/init.d/networking stop
+      DHCP=`grep -c 'iface eth0 inet dhcp' /etc/network/interfaces`
+      if [ "$DHCP" -eq "1" ]; then
+         echo "Starting DHCP on eth0"
+         /etc/init.d/udhcpc start
+      fi
+      /etc/init.d/networking start
+   fi
+fi
+sleep 2
+
+# Do own extras
+if [ -e /etc/ownscript.sh ]; then
+   /etc/ownscript.sh &
+fi
+
+# Try and synchronise time
+if [ -e /sbin/ntpdate ]; then
+   echo "Set internet time"
+   (/sbin/ntpdate de.pool.ntp.org; /bin/fp_control -sst) &
+else
+   if [ -e /usr/sbin/time.sh ]; then
+      echo "Use transponder time"
+      /usr/sbin/time.sh &
+   fi
+fi
+
+#tuner workaround
+export FE_OFFSET=1
+
+echo "Start Neutrino" > /dev/vfd
+
+until false
+do
+   echo "Starting neutrino ->"
+   /usr/local/bin/neutrino
+   rtv=$?
+   echo "neutrino ended <- RTV: " $rtv
+   case "$rtv" in
+      0) echo "0"
+         echo "SHUTDOWN"
+         echo "Shutdown" > /dev/vfd
+         init 0;;
+      1) echo "1"
+         echo "REBOOT"
+         echo "Reboot" > /dev/vfd
+         init 6;;
+      *) echo "*"
+         echo "ERROR"
+         echo "Error" > /dev/vfd
+         init 6;;
+   esac
+done
+
 #never reached
-echo "REBOOT SPARK-7162" > /dev/vfd
-echo "REBOOT SPARK-7162"
+echo "Reboot SPARK7162" > /dev/vfd
+echo "REBOOT SPARK7162"
 init 6
